### PR TITLE
Use refined types from dataflow analysis in generic method inference

### LINKED ISSUE #1287: For generic method inference, use refined type of locals
Consider:

https://github.com/uber/NullAway/blob/c187bf593f8a2979ca9770cb7849619f334daef4/nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java#L775-L800

Our generic method inference currently does not work correctly for this case, as it incorrectly assumes `x` is `@NonNull` based on its declaration.  Instead, inference should get nullability of local variables based on what is computed by our flow-sensitive type refinement, which in this case would be `@Nullable` for `x`.

This is a subtle change, since dataflow analysis also needs to invoke inference (see #1262), and so we have a cyclic dependence; will have to manage this carefully.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1287 

In generic method inference, we now try to obtain a refined type from dataflow-based type inference for arguments when generating constraints.  This introduces a recursive dependence between dataflow analysis and generic method inference, which we handle as follows.  We track whether generic method inference has been invoked from dataflow by passing a `calledFromDataflow` parameter.  When the parameter is true, generic method inference calls a new API to get the _current_ dataflow fact for the argument from the running dataflow analysis, avoiding a recursive run.  Since this may not be the fact in the final fixed point of dataflow, we skip caching of generic method inference results when it is invoked from the dataflow analysis.  This may skip caching unnecessarily in some cases, but we prefer to make correctness more obvious for now; we can optimize further in the future if needed.

## Summary by CodeRabbit

* **New Features**
  * Dataflow-aware argument/type refinement for improved nullness precision.
  * Ability to query in-flight ("running") dataflow nullness and control whether analysis runs.
  * Utility to strip nullable annotations from types.

* **Bug Fixes**
  * Guarded caching and path-aware propagation to avoid reusing dataflow-dependent inference results.

* **Tests**
  * Re-enabled a test, added dataflow/loop/local-variable tests, and updated diagnostics.

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java [hunk 1]
```diff
@@ -1160,7 +1284,7 @@ public void inferenceFromDataflow() {
             "    // to ensure that dataflow runs",
             "    Object x = new Object(); x.toString();",
             "    Object y = null;",
-            "    // BUG: Diagnostic contains: passing @Nullable parameter 'y' where @NonNull is required",
+            "    // BUG: Diagnostic contains: dereferenced expression id(y) is @Nullable",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:1287]: Nice! This feels more intuitive to me too.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java [hunk 2]
```diff
@@ -802,6 +801,131 @@ public void firstOrDefaultLocalVarParam() {
...
+            "    }",
+            "    void testNegative() {",
+            "        String s = \"hello\";",
+            "        String t = id(s);",
+            "        t.hashCode();",
+            "    }",
+            "    String field = \"hello\";",
+            "    void testField() {",
+            "        String s = null;",
+            "        // BUG: Diagnostic contains: Failed to infer type argument nullability",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:830]: Uh? Curious about this one, shouldn't it be assignment of `@Nullable` value to `@NonNull` field without further issue?

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java [hunk 3]
```diff
@@ -802,6 +801,131 @@ public void firstOrDefaultLocalVarParam() {
...
+            "    void testUnsupported() {",
+            "        String s = \"hello\";",
+            "        // dataflow can't prove the argument is non-null",
+            "        // BUG: Diagnostic contains: passing @Nullable parameter 's == null ? null : s'",
+            "        String t = id(s == null ? null : s);",
+            "        t.hashCode();",
+            "    }",
+            "}")
+        .doTest();
+  }
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:927]: Can we also add the exact test case from #1287 somewhere and link the issue? :)

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java [hunk 4]
```diff
@@ -802,6 +801,131 @@ public void firstOrDefaultLocalVarParam() {
...
+            "        if (field != null) {",
+            "            String t = id(field);",
+            "            t.hashCode();",
+            "        }",
+            "    }",
+            "    void testUnsupported() {",
+            "        String s = \"hello\";",
+            "        // dataflow can't prove the argument is non-null",
+            "        // BUG: Diagnostic contains: passing @Nullable parameter 's == null ? null : s'",
+            "        String t = id(s == null ? null : s);",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:922]: Interesting. Out of scope for this PR, but wonder if we can warn about redundant null checking here (I recall we discussed this years ago in some other context and decided against it? Likely due to to some redundant checks potentially being needed for false negatives in NullAway? e.g. due to concurrency? But I don't really recall)

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 5]
```diff
@@ -102,6 +104,22 @@ private static final class InferenceFailure implements MethodInferenceResult {
   private final Config config;
   private final Handler handler;
 
+  /**
+   * Was this code invoked from dataflow? Used to avoid infinite recursion.
+   *
+   * @see
+   *     com.uber.nullaway.dataflow.AccessPathNullnessPropagation#genericReturnIsNullable(MethodInvocationNode)
+   */
+  private boolean calledFromDataflow = false;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Maybe not quite yet, but I wonder if we will end up needing a `GenericsChecks.context` object with more information specific to where `GenericsChecks` is being run on. Also, do we re-use these objects? If not, I'd consider checking if we can make this final and set it when creating the `GenericsChecks` object.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 6]
```diff
@@ -714,17 +750,90 @@ private void generateConstraintsForParam(
...
+    }
+    Symbol argumentSymbol = ASTHelpers.getSymbol(argument);
+    if (argumentSymbol == null) {
+      return argumentType;
+    }
+    TreePath currentPath = path != null ? path : state.getPath();
+    // this is a bit sketchy, as it may not actually be the valid tree path to the argument.
+    // However, all we need the path for is to discover the enclosing method/lambda/initializer, and
+    // for that purpose this should be sufficient.
+    TreePath argumentPath = new TreePath(currentPath, argument);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:831]: Are we constructing this tree path because if `currentPath` happens to already be a method or lambda, then `findEnclosingMethodOrLambdaOrInitializer` will skip it in resolution? Or why?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 7]
```diff
@@ -714,17 +750,90 @@ private void generateConstraintsForParam(
...
+        String annotationName = annot.type.toString();
+        if (Nullness.isNullableAnnotation(annotationName, config)) {
+          removedNullable = true;
+          continue;
+        }
+        updatedAnnotations.append(annot);
+      }
+      Verify.verify(removedNullable);
+      return TYPE_METADATA_BUILDER.cloneTypeWithMetadata(
+          argumentType, TYPE_METADATA_BUILDER.create(updatedAnnotations.toList()));
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Nit/optional: Should we make a `TypeSubstitutionUtils.typeMinusAnnot(...)` or even `TypeSubstitutionUtils.removeNullableAnnotions(...)` and move this logic there for symmetry? Not sure of the layering between `TypeSubstitutionUtils` and `Nullness`, but otherwise this doesn't seem to depend on anything in `GenericsChecks` but the type and `Config`.

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java [hunk 8]
```diff
@@ -1152,9 +1153,18 @@ private boolean genericReturnIsNullable(MethodInvocationNode node) {
     if (node != null && config.isJSpecifyMode()) {
       MethodInvocationTree tree = node.getTree();
       if (tree != null) {
-        Nullness nullness =
-            genericsChecks.getGenericReturnNullnessAtInvocation(
-                ASTHelpers.getSymbol(tree), tree, node.getTreePath(), state);
+        // set flag that we are calling from dataflow to avoid infinite recursion, and verify that
+        // we are not already in a recursion.
+        verify(!genericsChecks.isCalledFromDataflow());
+        genericsChecks.setCalledFromDataflow(true);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java]: Ah, never mind my comment at https://github.com/uber/NullAway/pull/1309/files#diff-82d66c6ba15b87acc24509d7a3440bbe7606944197b929733d315fbe0a025435R113 below, I guess we are indeed using `GenericsChecks` as a re-usable singleton, not per invocation, so we can't make two instances with a `final calledFromDataflow`.

Threading the parameter might be a reasonable follow up, but I do see the description saying this was involved.

**Review by lazaroclapp — COMMENTED** [review]
Looks good to me! Agree that the field setup is a bit of a code smell, but seems like it works and I can see threading the "is in dataflow" context being painful (we might want to look into aggregating a lot of the context for `GenericChecks` and figuring out a principled way to pass it around, since that whole processing is very context dependent, but I would do that as it's own PR in any case).

Other than that, a bunch of minor suggestions/nits, the main thing I'd expect to see is the test case from #1287, unless I missed it somehow :)

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:830]: Sorry, this is because for this test we enable warnings for failed inference (the test code starts with `makeHelperWithInferenceFailureWarning()`).  I did that because I wanted to confirm here that inference would fail due to passing `null` as a parameter.  Before, inference would succeed (since we didn't call into dataflow and assumed `s` was `@NonNull`), and then we would get the error you expected.  If you like, I can do another version of this test without inference failures enabled to ensure we get the right error message.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:927]: This test was already present but `@Ignore`d.  This diff removes the `@Ignore` at line 776 enabling the test.  Sorry this wasn't clear.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java (hunk 4 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:922]: It would be interesting to explore in the future and could expose some bugs.  FWIW, Error Prone how has a separate checker that does a form of this; https://github.com/google/error-prone/pull/5253.  But I don't think it will find redundant checks on local variables.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 7 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Yes, you're right, that will most likely be reusable; I'll do that refactor.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 6 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:831]: It's because in the `getNullnessFromRunning()` / `getNullness()` calls further down, the nullness returned is the nullness of the leaf of the passed-in `TreePath`.  I'll add a comment to clarify.

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java (hunk 8 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java]: I did try threading the parameter, but it ended up adding parameters to other public API methods, which would end up polluting the call sites of those methods when really dataflow only calls `getGenericReturnNullnessAtInvocation`.  I could do it, but it doesn't seem clean.  I'll double check and make sure it's as bad as I thought.
