### PR TITLE
Reports all errors regarding passing nullable where nonnull required in one single method call

### LINKED ISSUE #502: Reporting only the first occurrence of passing nullable
In the following code, four `nullable` parameters are passed to a method which expect `nonnull` for all params and `NullAway` reports **only one** error associated to the firs parameter instead of all four places.

```java
public class Item {

    Item(Object a, Object b, Object c, Object d, Object e, Object f){ }

    public void set(){
        Item item = new Item(null, null, new Object(), null, null, new Object());
    }
}
```

And below is the set of all errors reported by `NullAway`:
```java
Item.java:10: error: [NullAway] passing @Nullable parameter 'null' where @NonNull is required
        Item item = new Item(null, null, new Object(), null, null, new Object());
                             ^
    (see http://t.uber.com/nullaway )
1 error

```

The version I am using to generate the above output with `gradle` is:
```
annotationProcessor "com.uber.nullaway:nullaway:0.9.2"
```

### PR DESCRIPTION
**Pull request by nimakarimipour**
fixes #502

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -1348,13 +1350,15 @@ private Description handleInvocation(
             "passing @Nullable parameter '"
                 + state.getSourceForNode(actual)
                 + "' where @NonNull is required";
-        return errorBuilder.createErrorDescriptionForNullAssignment(
-            new ErrorMessage(MessageTypes.PASS_NULLABLE, message),
-            actual,
-            buildDescription(actual),
-            state);
+        passNullableDescriptionSet.add(
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:1353]: Why not just call `state.reportMatch()` in each loop iteration, rather than collecting the descriptions in a set?  Not a huge difference, but the code would be slightly simpler if you eliminated the set

File: nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java [hunk 2]
```diff
@@ -3123,4 +3123,32 @@ public void springAutowiredConstructorTest() {
             "}")
         .doTest();
   }
+
+  @Test
+  public void multipleNullableParamPassTest() {
+    defaultCompilationHelper
```
Comment (msridhar) [inline nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java:3129]: Since these tests don't really check for the desired behavior, I think we can just delete them.  I don't think the Error Prone tests allow for checking for multiple errors on the same line.  @nimakarimipour confirmed to me that he tested outside Error Prone and saw the desired output

**Review by msridhar — CHANGES_REQUESTED** [review]
Thanks for the fix!  A couple of comments

**Review by msridhar — APPROVED** [review]
LGTM
