### PR TITLE
Initial handling of constructor diamond operators

### LINKED ISSUE #1451: Incompatible types error with `@Nullable Void`
Following [JSpecify recommandation](https://github.com/jspecify/jspecify/issues/51), I have tried to update a Spring callback from `Void` to `@Nullable Void`, but I get the following error with https://github.com/sdeleuze/spring-framework/commit/retry-task-nullability when running `./gradlew build`.

```
> Task :spring-core:compileJava FAILED
/Users/sdeleuze/workspace/spring-framework/spring-core/src/main/java/org/springframework/core/retry/support/RetryTask.java:200: error: [NullAway] incompatible types: TaskCallback<@Nullable Void, RuntimeException> cannot be converted to TaskCallback<V, E>
                RetryTask<@Nullable Void, RuntimeException> rt = new RetryTask<>(TaskCallback.from(task), retryTemplate) {
```

I am not 100% sure yet that's a NullAway bug, but could be so I would welcome a feedback.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1451 

This adds partial support for diamond operators, sufficient to fix #1451.  We still need to fully support diamonds in generic method inference.

## Summary by CodeRabbit

* **New Features**
  * Context- and path-aware type inference for Java diamond (<>) constructor calls using surrounding assignment/return/parameter contexts.

* **Enhancements**
  * Preserves explicit type arguments and more accurately propagates inferred generics and nullability across assignments, returns, and calls.
  * Better parenthesized-expression handling with updated path-aware context tracking; error reporting and nullability checks reflect these inferences.

* **Tests**
  * Added tests covering diamond inference, nested/parenthesized constructors, parameter/return scenarios, and nullability interactions.

* **Public API**
  * Added a small public utility that returns an expression paired with an updated traversal state for path-aware processing.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 1]
```diff
@@ -522,6 +536,149 @@ private void reportInvalidOverridingMethodParamTypeError(
...
+    AtomicReference<@Nullable Type> formalParamTypeRef = new AtomicReference<>();
+    new InvocationArguments(invocationTree, invocationType)
+        .forEach(
+            (arg, pos, formalParamType, unused) -> {
+              if (ASTHelpers.stripParentheses(arg) == argumentTree) {
+                formalParamTypeRef.set(formalParamType);
+              }
+            });
+    return formalParamTypeRef.get();
+  }
```
[the remark this answers is not in the document]
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:635]: `InvocationArguments.forEach` does more than a straightforward indexed loop, it has special-case handling for varargs, etc.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericDiamondTests.java [hunk 2]
```diff
@@ -0,0 +1,219 @@
...
+                Bar(Foo<T> foo) {
+                }
+              }
+              void testNegative() {
+                // should be legal
+                Bar<@Nullable Void> b = new Bar<>(Foo.make());
+              }
+              void testPositive() {
+                // BUG: Diagnostic contains: incompatible types: Foo<@Nullable String> cannot be converted to Foo<String>
+                Bar<String> b = new Bar<>(Foo.makeNullableStr());
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericDiamondTests.java:38]: Just out of curiosity, does:

```
Bar<Void> b = new Bar<>(Foo.make());
```

Also report an error?

(In general, that thread about `@Nullable Void` vs `Void` still feels like a weird gotcha in the type system regardless of what decision was taken, "nothing or null" is a silly type, but I understand the wish for consistency)

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 3]
```diff
@@ -434,14 +436,26 @@ private void reportInvalidOverridingMethodParamTypeError(
...
+        if (fromAssignmentContext != null) {
+          return fromAssignmentContext;
+        }
       }
-      return typeWithPreservedAnnotations(paramTypedTree);
+      if (newClassTree.getIdentifier() instanceof ParameterizedTypeTree paramTypedTree
+          && !paramTypedTree.getTypeArguments().isEmpty()) {
+        return typeWithPreservedAnnotations(paramTypedTree);
+      }
+      return ASTHelpers.getType(tree);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: What is this last case? Just `new` without either generics or a diamond operator, right? Do we need any of the [handling we have below for raw types](https://github.com/uber/NullAway/blob/d7e47726fb03af2e547e4cac648f45b840d5f290/nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java#L517) or that's only relevant to invocations that aren't `new ...`?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 4]
```diff
@@ -434,14 +436,26 @@ private void reportInvalidOverridingMethodParamTypeError(
...
-        && ((NewClassTree) tree).getIdentifier() instanceof ParameterizedTypeTree paramTypedTree) {
-      if (paramTypedTree.getTypeArguments().isEmpty()) {
-        // diamond operator, which we do not yet support; for now, return null
-        // TODO: support diamond operators
-        return null;
+    if (tree instanceof NewClassTree newClassTree) {
+      if (TreeInfo.isDiamond((JCTree) newClassTree)) {
+        if (newClassTree.getClassBody() != null) {
+          // Keep existing behavior for diamond anonymous classes, which are not yet fully
+          // supported.
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Might be worth linking an issue?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 5]
```diff
@@ -522,6 +536,145 @@ private void reportInvalidOverridingMethodParamTypeError(
...
+        if (methodSymbol != null) {
+          return methodSymbol.getReturnType();
+        }
+      }
+      return null;
+    }
+    if (parent instanceof MethodInvocationTree parentInvocation) {
+      if (isGenericCallNeedingInference(parentInvocation)) {
+        // TODO support full integration of diamond constructor calls with generic method inference
+        // for now, just give up and return null
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:589]: Worth linking #1470 here?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 6]
```diff
@@ -522,6 +536,145 @@ private void reportInvalidOverridingMethodParamTypeError(
...
+    }
+    return null;
+  }
+
+  /** Returns the inferred/declared formal parameter type corresponding to {@code argumentTree}. */
+  private @Nullable Type getFormalParameterTypeForArgument(
+      Tree invocationTree, Type.MethodType invocationType, Tree argumentTree) {
+    AtomicReference<@Nullable Type> formalParamTypeRef = new AtomicReference<>();
+    new InvocationArguments(invocationTree, invocationType)
+        .forEach(
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:628]: Bit annoying that there isn't a better way to preserve the arg number as we are going of the tree-path, this is an unnecessary (but likely fairly short) traversal. Nothing to address here, just wondering if the javac APIs could make this easier...

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 7]
```diff
@@ -522,6 +536,145 @@ private void reportInvalidOverridingMethodParamTypeError(
...
+            (arg, pos, formalParamType, unused) -> {
+              if (ASTHelpers.stripParentheses(arg) == argumentTree) {
+                formalParamTypeRef.set(formalParamType);
+              }
+            });
+    return formalParamTypeRef.get();
+  }
+
+  /** Finds the path to {@code target} within {@code rootPath}, or null when not found. */
+  private static @Nullable TreePath findPathToSubtree(TreePath rootPath, Tree target) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Same worry here. These sort of traversals, as opposed to keeping the current path in state somehow, is one of the reasons Checker Framework was slower than FBInfer/NullAway in the past, no? I guess this is not a traversal from the compilation unit root, but still feels like a bit of a potential smell.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 8]
```diff
@@ -1154,7 +1308,7 @@ public void checkTypeParameterNullnessForFunctionReturnType(
       // bail out of any checking involving raw types for now
       return;
     }
-    Type returnExpressionType = getTreeType(retExpr, state);
+    Type returnExpressionType = getTreeType(retExpr, withPathToSubtree(state, retExpr));
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Can we maintain these paths manually? Should we? I worry that `withPathToSubtree` is long term a dangerous method to have from a performance standpoint, but not sure exactly how bad maintaining a separate tree-path for each of these use cases would get.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericDiamondTests.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericDiamondTests.java:38]: Yes, this does lead to an error being reported (4babffe726de74582160edbe2b1bc7a64a57340e).  This `@Nullable Void` point came up again in a recent discussion and I did not sense any appetite to re-open the question :-)  We are not yet forcing users to write `@Nullable Void` everywhere, though probably we should do it at some point soon (in JSpecify mode)

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Good point!  We had tests for raw constructor invocations that passed without any checking here (probably due to defensive checking for raw types elsewhere).  But better to be consistent; fixed in 78501f2022a75123223755924d3e40da386b91e5 (and added a related helper function)

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 6 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:628]: Yeah, that information isn't preserved in the `TreePath` or any kind of side map, as far as I know.  I don't expect this to be too expensive.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 8 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: @lazaroclapp thanks for pushing me on this.  I dug in and rewrote the code so we don't need `withPathToSubtree` or `findPathToSubtree` anymore, by maintaining paths manually.  In particular, I added a method `com.uber.nullaway.NullabilityUtil#stripParensAndUpdateTreePath` that both strips parentheses from an expression and also updates a `VisitorState` to have a path to the nested expression (without the parens).

There might be some unhandled cases, but all the tests pass.  In the future we might find another case that needs handling, but we should then augment the manual path construction to do so.

**Comment by msridhar** [comment]
@coderabbitai review

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java [hunk 9]
```diff
@@ -730,4 +730,31 @@ public static ExpressionTree stripParensAndCasts(ExpressionTree expr) {
...
+   * @param expr a potentially parenthesised expression.
+   * @param state the VisitorState
+   * @return the same expression without parentheses, and the updated VisitorState
+   */
+  public static ExprTreeAndState stripParensAndUpdateTreePath(
+      ExpressionTree expr, VisitorState state) {
+    TreePath path = state.getPath();
+    if (path.getLeaf() != expr) {
+      // if the expression is not the leaf of the path, we can't update the path to point to the
+      // stripped expression, so we just return the original expression and state
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:752]: When do we hit this case? Isn't it just an error to pass an `ExpressionTree` and `VisitorState` here that don't match? Wondering what the trade-off is here for just throwing an exception / adding a pre-condition vs silently returning the input. (I know we don't want to crash needlessly, so obviously if there are legitimate cases where these two can diverge that aren't a huge bug in our code, I'd err on the side of not throwing... did we have a strict mode for tests where we can conditionally chose to crash if we are testing NullAway itself?)

To be clear, having this method feels like a big improvement over the extra traversals, though :)

**Review by lazaroclapp — APPROVED** [review]
LGTM with one nit / potential follow up consideration.

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java (hunk 9 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:752]: It turns out if we just throw here it fails a lot right now :-)  I don't want to fix all those cases in this PR, but I added an issue to track and a comment.  I agree we should fix, as it could improve inference results in some cases.
