### PR TITLE
Fix NPE inside NullAway when initializer methods use try-with-resources.

### LINKED ISSUE #176: NPE in NullAway.safeInitByCalleeBefore()
### What version of Error Prone/NullAway are you using?

error-prone version: 2.3.1
nullaway version: 0.4.6
BugPattern: NullAway

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Trying to build dropwizard-hibernate with Error Prone 2.3.1 and NullAway 0.4.6.

Failed Travis CI build: https://travis-ci.org/dropwizard/dropwizard/jobs/394031326#L5906-L5912
Dropwizard repository: https://github.com/dropwizard/dropwizard/tree/959182092d57debcc0c85f74b895b33ccb073431
Source file which makes the build fail: [`io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java:[50,32]`](https://github.com/dropwizard/dropwizard/blob/959182092d57debcc0c85f74b895b33ccb073431/dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java#L50)

Unfortunately I'm currently unable to provide a minimal example to reproduce the issue, but the build of dropwizard-hibernate reproducibly fails when analyzing `UnitOfWorkAwareProxyFactoryTest`.

### What did you expect to see?

The build should be successful or at least emit proper warnings by Error Prone/NullAway.

FWIW, the build succeeds with Error Prone 2.2.0 and NullAway 0.3.2.

### What did you see instead?

The build fails with a NullPointerException in NullAway.

The stack trace of the NullPointerException looks similar to the one in #144.

### PR DESCRIPTION
**Pull request by lazaroclapp**
Fixes #176.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -815,15 +815,21 @@ private boolean fieldAlwaysInitializedBeforeRead(
         // Hack: Handling try{...}finally{...} statement, see getSafeInitMethods
         if (curStmt.getKind().equals(Tree.Kind.TRY)) {
           TryTree tryTree = (TryTree) curStmt;
+          // ToDo: Should we check initialization inside tryTree.getResources ? What is the scope of
+          // that initialization?
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: This is actually important if we are supporting code with `try-with-resources` in general, but doing this PR first will at least fix up the crash, which is higher priority.
