### PR TITLE
Fail if NullAway is run in JSpecify mode with an incompatible javac version / configuration

### LINKED ISSUE #1310: Fail early with a JDK not compatible with the JSpecify mode
Discussed very quickly with @msridhar yesterday, so I create a related issue to provide more details.

I see more and more projects using NullAway with JSpecify mode enabled on JVM that does not support it:
 - Java 17 to 21.0.7
 - Java 21.0.8+ without the `-XDaddTypeAnnotationsToSymbol=true` flag

There is no clear breakage, builds are not always reproducible and users are confused and not aware this is not supported, even if this is specified in the wiki.

Would be nice to fail fast with a related error message when NullAway is running on an unsupported Java version when the JSpecify mode is enabled.

Ideally we would not hardcode the Java versions (since a Java 17 backport of the `-XDaddTypeAnnotationsToSymbol=true` flag may come), but detect if possible the broken annotation processor behavior. If not possible, detecting Java version would be better than what we have today.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1310

NullAway now fails with an exception if run on an incompatible javac configuration, i.e., a configuration that does not support reading type use annotations from bytecode (see https://github.com/uber/NullAway/wiki/JSpecify-Support#supported-jdk-versions).  Specifically, NullAway fails if it is running on JDK version before 22 and the `-XDaddTypeAnnotationsToSymbol=true` has not been passed to `javac`.  Note that `javac` versions that do not recognize the `-XDaddTypeAnnotationsToSymbol` flag simply ignore it, so this check does not ensure we are on a compatible JDK.  But, it's better than nothing, and doing a more careful check would be hard, since some distributions of the same JDK version may not support the flag.  Also, there is hope for this flag to be backported to JDK 17u, and this way we won't need to change our logic when that happens.  Documentation of supported versions is at https://github.com/uber/NullAway/wiki/JSpecify-Support#supported-jdk-versions and that URL is included in the error message.  When this PR lands, we will update the docs to indicate the stronger version requirement.

Rather than passing `"-XDaddTypeAnnotationsToSymbol=true"` in many places in our test code, we introduce a `JSpecifyJavacConfig` test helper class and use it wherever we want to run tests in JSpecify mode, to ensure the right flags are passed together.

## Summary by CodeRabbit

* **Bug Fixes**
  * Added JDK version validation for JSpecify mode, ensuring compatibility with JDK 22+ and required type annotation configurations.

* **Tests**
  * Enhanced test infrastructure to centralize JSpecify configuration handling across test suites.
  * Added validation test for JDK compatibility requirements.

### CODE REVIEW

**Comment by msridhar** [comment]
@coderabbitai review

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -1703,6 +1706,16 @@ public Description matchClass(ClassTree tree, VisitorState state) {
     if (codeAnnotationInfo == null) {
       codeAnnotationInfo = CodeAnnotationInfo.instance(state.context);
     }
+    if (!checkedJDKVersionForJSpecifyMode) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:1709]: If I remember correctly, we need to defer this to here because any exception in the `NullAway` constructor just causes it to default to the no-config constructor, right?

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 2]
```diff
@@ -2813,6 +2826,24 @@ private static ExpressionTree stripParensAndCasts(ExpressionTree expr) {
     return expr;
   }
 
+  private static boolean isValidJavacConfigForJSpecifyMode(VisitorState state) {
+    // Ensure that in JSpecify mode, either (1) we are running on JDK 22 or above, or (2) the user
+    // has passed -XDaddTypeAnnotationsToSymbol=true to javac.
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Nit: maybe move this to a javadoc comment? I know it's a private method, but if this comment describes the behavior of the full method, then that makes sense to me and it will cause the info to appear on hover in the IDE.

Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Also, `NullAway.java` is huge, and this method uses nothing from it other than `VisitorState`. Maybe it can be moved to somewhere else? (Possibly `Config`, thought right now we have only the `Config` object interface there, so maybe that's also not ideal...)

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 3]
```diff
@@ -2813,6 +2826,24 @@ private static ExpressionTree stripParensAndCasts(ExpressionTree expr) {
...
+    Runtime.Version version = Runtime.version();
+    if (version.feature() < 22) {
+      Options opts = Options.instance(state.context);
+      String key = "addTypeAnnotationsToSymbol";
+      if (!opts.isSet(key)) {
+        return false;
+      }
+      String v = opts.get(key);
+      return v.isEmpty() || Boolean.parseBoolean(v);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Is `-XDaddTypeAnnotationsToSymbol` equivalent to `-XDaddTypeAnnotationsToSymbol=true`? (Trying to figure out this `isEmpty()` check, might need a very short comment)

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:1709]: It's because we need access to a `VisitorState` object, which is not provided to the constructor.  I can add an explanatory comment.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Good catch!  I tested and these two things are _not_ equivalent; we need `-XDaddTypeAnnotationsToSymbol=true`.  I will fix the code and get rid of the `isEmpty()` call.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Moved the code out into a separate class, combining with the test utility methods

**Comment by nimakarimipour** [comment]
@coderabbitai talk to me.
