### PR TITLE
Switch parameter overriding handler to use `Nullness[]`

### LINKED ISSUE #645: Investigate and resolve performance regression from #639
Context: https://github.com/uber/NullAway/pull/641#issuecomment-1232134787 and previous comments in #641

### PR DESCRIPTION
**Pull request by msridhar**
The performance improvement from this change is very small at best, and it doesn't seem to fully remove the recent performance regression.  But, this change clearly makes the code more efficient in the common case, and I think a bit easier to read as well.  So we should keep it.  Any remaining performance regression (#645) is probably just due to doing more checking than we were doing before (to fix bugs), so we can tolerate it.

Fixes #645

### CODE REVIEW

**Comment by msridhar** [comment]
For the record, here are the perf results I got for running all benchmarks with this change:
```
Benchmark                          Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile      thrpt   25  10.734 ± 0.078  ops/s
CaffeineBenchmark.compile         thrpt   25   2.480 ± 0.010  ops/s
DFlowMicroBenchmark.compile       thrpt   25  28.696 ± 0.224  ops/s
NullawayReleaseBenchmark.compile  thrpt   25   1.515 ± 0.020  ops/s
```

And this is what we had just after updating to CF 3.24:
```
Benchmark                          Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile      thrpt   25  10.739 ± 0.089  ops/s
CaffeineBenchmark.compile         thrpt   25   2.517 ± 0.013  ops/s
DFlowMicroBenchmark.compile       thrpt   25  28.917 ± 0.149  ops/s
NullawayReleaseBenchmark.compile  thrpt   25   1.509 ± 0.013  ops/s
```

I did a separate single run for Caffeine and got this:
```
Benchmark                   Mode  Cnt  Score   Error  Units
CaffeineBenchmark.compile  thrpt   25  2.493 ± 0.011  ops/s
```

This result is (barely) within the noise of the CF 3.24 run.  Bottom line, I think we still have a slight perf regression on Caffeine, but it's getting hard to measure.

**Comment by lazaroclapp** [comment]
This also looks like no measurable difference between after this PR:

```
Benchmark                          Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile      thrpt   25  10.734 ± 0.078  ops/s
CaffeineBenchmark.compile         thrpt   25   2.480 ± 0.010  ops/s
DFlowMicroBenchmark.compile       thrpt   25  28.696 ± 0.224  ops/s
NullawayReleaseBenchmark.compile  thrpt   25   1.515 ± 0.020  ops/s
```

And after #646 (from your [comment](https://github.com/uber/NullAway/pull/646#issuecomment-1232430226) there):

```
Benchmark                          Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile      thrpt   25  10.690 ± 0.060  ops/s
CaffeineBenchmark.compile         thrpt   25   2.479 ± 0.010  ops/s
DFlowMicroBenchmark.compile       thrpt   25  28.588 ± 0.383  ops/s
NullawayReleaseBenchmark.compile  thrpt   25   1.507 ± 0.018  ops/s
```

Although all measurements _are_ higher after this change, just still within the noise, and the data type change makes sense to me either way... so probably worth making the change anyways. Let me review.

File: nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java [hunk 1]
```diff
@@ -182,16 +181,17 @@ Nullness onOverrideMethodInvocationReturnNullability(
    * @param isAnnotated A boolean flag indicating whether the called method is considered to be
    *     within isAnnotated or unannotated code, used to avoid querying for this information
    *     multiple times within the same handler chain.
-   * @param argumentPositionNullness The argument position to nullness map computed by upstream
-   *     handlers and/or the base analysis (though information from the base analysis is allowed to
-   *     be incomplete/sparse at this point).
-   * @return The updated argument position to nullness map, as computed by the current handler.
+   * @param argumentPositionNullness Nullness info for each argument position as computed by
+   *     upstream handlers and/or the base analysis. Some entries may be {@code null}, indicating
+   *     upstream analysis and handlers model the parameter as unannotated.
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java:186]: I wonder if "as unannotated" is the right term once you mention handlers... it's definitely possible for handlers to have a more specific opinion on unannotated code and thus an explicit value here (e.g. `RestrictiveAnnotationHandler` will explicitly mark `@Nullable` parameters within unannotated code as `NULLABLE` here). I guess "model the parameter as nullness-unknown, which usually indicates parameters within unannotated code for which no handler specifies any particular nullability"?

**Review by lazaroclapp — APPROVED** [review]
Minor nit about javadoc, but otherwise this looks good to me!

File: nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java:186]: Sure, I will clarify
