### PR TITLE
Bug fix with type substitutions after inference

### LINKED ISSUE #1267: JSpecify inference: fix bug in type substitutions exposed by Caffeine
Shown in `nullableWildcardFromCaffeine` test case from #1248.  This is something involving `Type` objects getting compared by object identity.  We are creating new `Type` objects somewhere and then our lookups in our nullability inference map don't match.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1267 

Due to possible type mutations, e.g., when substituting for bounds, sometimes we see `TypeVar`s in types that are not the same object as in the original method type for which we performed inference.  Previously, we wouldn't substitute properly in such cases.  Here, we collect all `TypeVar`s with the same `Symbol` observed during inference and substitute for all of them, fixing the problem.  This makes the Caffeine integration test green again.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved nullability handling for generics: all matching occurrences of a type variable are now annotated with a synthetic nullable marker, ensuring consistent analysis and avoiding missed substitutions across repeated type-variable occurrences.
* **Tests**
  * Updated tests to reflect improved generic inference behavior; removed prior suppression/workarounds.

### CODE REVIEW

**Comment by msridhar** [comment]
@coderabbitai review

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 1]
```diff
@@ -1450,12 +1463,15 @@ public boolean isNullableAnnotated(Type type) {
...
    */
-  public static Type getSyntheticNullAnnotType(VisitorState state) {
-    Names names = Names.instance(state.context);
-    Symtab symtab = Symtab.instance(state.context);
-    Name name = names.fromString("nullaway.synthetic");
-    Symbol.PackageSymbol packageSymbol = new Symbol.PackageSymbol(name, symtab.noSymbol);
-    Name simpleName = names.fromString("Nullable");
-    return new Type.ErrorType(simpleName, packageSymbol, Type.noType);
+  private Type getSyntheticNullAnnotType(VisitorState state) {
+    if (syntheticNullAnnotType == null) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1467]: Are we comparing this for identity in any way in which we would need to care about synchronization here? Or is either the case that (a) we don't care if we end up with multiple copies of the synthetic type / this is only a performance optimization, and/or (b) this class is never shared across threads (I actually don't fully recall how much parallelism there is in NullAway / EP overall beyond different `javac` instances in a parallel build having a copy of the plugin :) ).

**Review by lazaroclapp — APPROVED** [review]
LGTM!

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1467]: This is a combo of everything 🙂 `Type`s do get compared by object equality in certain places (as I learned when fixing this issue), so seems good to only have one of these synthetic type objects floating around.  Should be a small improvement in performance.  And, this class should not be shared across threads; in a parallel build each thread should have its own `NullAway` instance, which creates its own `GenericsChecks` instance.  `javac` itself doesn't support multithreading in a single instance AFAIK

Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1467]: That matches what I thought re: NullAway / javac plugins, but it's good to have confirmation. Cool! :)
