### PR TITLE
Model parseXXX methods of boxed primitives as having @NonNull parameter

### LINKED ISSUE #269: Model parseXXX methods of boxed primitives as having @NonNull parameter
E.g., the parameter of `Long.parseLong(String)` should not be `null` or a `NumberFormatException` gets thrown.  We should model all the `parseXXX` methods of all the `java.lang` boxed primitive types.

### PR DESCRIPTION
**Pull request by shas19**
E.g., the parameter of Long.parseLong(String) should not be null or a NumberFormatException gets thrown. We should model all the parseXXX methods of all the java.lang boxed primitive types.

Following methods are added 
1. parseInt 2. parseFloat 3. parseShort 4. parseLong 5. parseDouble 6. parseByte 7. parseBoolean

Fixes #269
Added unit tests.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java [hunk 1]
```diff
@@ -304,6 +304,13 @@ private static LibraryModels loadLibraryModels() {
             .put(methodRef("java.util.ArrayDeque", "offer(E)"), 0)
             .put(methodRef("java.util.ArrayDeque", "push(E)"), 0)
             .put(methodRef("java.util.ArrayDeque", "<T>toArray(T[])"), 0)
+            .put(methodRef("java.lang.Integer", "parseInt(java.lang.String)"), 0)
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java]: Can we also handle overloads that take a radix, like [this one](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#parseInt(java.lang.String,%20int))?  I think `Long` has one too, not sure about others

Comment (shas19) [reply nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java]: done 👍

**Comment by msridhar** [comment]
Thanks @shas19!
