### PR TITLE
Propagate more nullability info to lambdas known to be invoked synchronously

### LINKED ISSUE #941: Variable checked non-null outside a `forEach` or `Stream` lambda triggers an error
The most common source of irrelevant errors we see in Spring Framework codebase with NullAway is this use case where the static analysis is not able to consider `this.resolvedDataSources` non-nullable in code found in lambdas:
```java
public void initialize() {
	if (this.targetDataSources == null) {
		throw new IllegalArgumentException("Property 'targetDataSources' is required");
	}
	this.resolvedDataSources = CollectionUtils.newHashMap(this.targetDataSources.size());
	this.targetDataSources.forEach((key, value) -> {
		Object lookupKey = resolveSpecifiedLookupKey(key);
		DataSource dataSource = resolveSpecifiedDataSource(value);
		this.resolvedDataSources.put(lookupKey, dataSource);
	});
}
```

Such code generates the following error:
```
/Users/sdeleuze/workspace/spring-framework/spring-jdbc/src/main/java/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.java:145: error: [NullAway] dereferenced expression this.resolvedDataSources is @Nullable
                        this.resolvedDataSources.put(lookupKey, dataSource);
```
It is true that some lambda could be executed at a later point when the value has changes, but the fact that by default this is not consider as a valid use case generates a lot of irrelevant errors, and I would like to avoid to add an artificial check inside the lambda.

Could that be refined?

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #941

We propagate full nullability info from the enclosing context to callbacks passed to `Map.forEach`, `Iterable.forEach`, `List.removeIf`, and all methods on `java.util.stream.Stream`

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+            "    private @Nullable MyMap<Object, Object> resolved;",
+            "    static class MyMap<K,V> {",
+            "        public void forEach(BiConsumer<Object, Object> consumer) {}",
+            "        public void put(Object key, Object value) {}",
+            "    }",
+            "    public void initialize() {",
+            "        if (this.target == null) {",
+            "            throw new IllegalArgumentException();",
+            "        }",
+            "        this.resolved = new MyMap<>();",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java:82]: Maybe use a type other than `MyMap` for `this.resolved` here? Got a bit confused think that was what changed the test case, but it doesn't, right? What matters is that `target` is `MyMap`.

File: nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+            "public class Test {",
+            "    private @Nullable Object f;",
+            "    public void test1() {",
+            "        if (this.f == null) {",
+            "            throw new IllegalArgumentException();",
+            "        }",
+            "        List<Object> l = new ArrayList<>();",
+            "        l.forEach(v -> System.out.println(v + this.f.toString()));",
+            "        Iterable<Object> l2 = l;",
+            "        l2.forEach(v -> System.out.println(v + this.f.toString()));",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java:111]: Worth adding a case where we set `this.f = null` then do one of these and show it now reports an error?

File: nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java [hunk 3]
```diff
@@ -191,7 +191,8 @@ private Stream<T> test1(Stream<T> stream) {
 
     private Stream<T> test2(Stream<T> stream) {
       Preconditions.checkNotNull(ref);
-      // BUG: Diagnostic contains: dereferenced expression ref is @Nullable
+      // no error since we propagate nullability facts to stream callbacks, which
+      // in sane code are invoked soon after the stream is created
```
Comment (lazaroclapp) [inline nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java:195]: I guess I go a bit back and forth between "this is probably safe" and "restricting it to cases where the stream doesn't escape the method will remove most false positives too and be safer". Your call.

File: nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java [hunk 4]
```diff
@@ -199,8 +201,9 @@ public Optional<ErrorMessage> onExpressionDereference(
   }
 
   @Override
-  public boolean includeApInfoInSavedContext(AccessPath accessPath, VisitorState state) {
-    return false;
+  public Predicate<AccessPath> getAccessPathPredicateForNestedMethod(
+      TreePath path, VisitorState state) {
+    return CompositeHandler.FALSE_AP_PREDICATE;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java:206]: Why is this a field of `CompositeHandler`, rather than say `Handler` (where we define e.g. `NullnessHint`)

File: nullaway/src/main/java/com/uber/nullaway/handlers/CompositeHandler.java [hunk 5]
```diff
@@ -252,13 +254,37 @@ public Optional<ErrorMessage> onExpressionDereference(
...
+   * An AccessPath predicate that always returns false. Used for optimizing
+   * getAccessPathPredicateForNestedMethod.
+   */
+  static final Predicate<AccessPath> FALSE_AP_PREDICATE = ap -> false;
+
+  /**
+   * An AccessPath predicate that always returns true. Used for optimizing
+   * getAccessPathPredicateForNestedMethod.
+   */
+  static final Predicate<AccessPath> TRUE_AP_PREDICATE = ap -> true;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/CompositeHandler.java:267]: Why part of `CompositeHandler` vs `Handler`? Also, maybe we want `Handler.AccessPathPredicates.[TRUE|FALSE]_AP_PREDICATE`? (We can always static import to avoid repetition)

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java [hunk 6]
```diff
@@ -164,17 +165,18 @@ private boolean isOptionalContentNullable(
...
+        final Element e = ap.getRoot();
+        if (e != null) {
+          return e.getKind().equals(ElementKind.LOCAL_VARIABLE)
+              && ap.getElements().get(0).getJavaElement() instanceof OptionalContentVariableElement;
+        }
       }
-    }
-    return false;
+      return false;
+    };
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:179]: Unrelated to this PR, but... are we missing unit tests for this handler? Or is Codecov wrong?

File: nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java [hunk 7]
```diff
@@ -327,15 +329,16 @@ Optional<ErrorMessage> onExpressionDereference(
...
-   * @param accessPath The access path that needs to be checked if filtered.
+   * @param path The tree path to the node for the nested method.
    * @param state The current visitor state.
-   * @return true if the nullability information for this accesspath should be treated as part of
-   *     the surrounding context when processing a lambda expression or anonymous class declaration.
+   * @return A predicate that determines which access paths should be preserved when analyzing the
+   *     nested method.
    */
-  boolean includeApInfoInSavedContext(AccessPath accessPath, VisitorState state);
+  Predicate<AccessPath> getAccessPathPredicateForNestedMethod(TreePath path, VisitorState state);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java:341]: Interesting that our existing stream handling support doesn't really use this Handler method, it seems... I assume because of how handlers work that we just end up composing the information about `x` we get from the stream handler when looking at `s.filter(x -> ...).map(x -> ...)` with the info this gives us about the APs from the closure?

File: nullaway/src/main/java/com/uber/nullaway/handlers/SynchronousCallbackHandler.java [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+      Suppliers.typeFromString("java.util.stream.Stream");
+
+  @Override
+  public Predicate<AccessPath> getAccessPathPredicateForNestedMethod(
+      TreePath path, VisitorState state) {
+    Tree leafNode = path.getLeaf();
+    Preconditions.checkArgument(
+        leafNode instanceof ClassTree || leafNode instanceof LambdaExpressionTree,
+        "Unexpected leaf type: %s",
+        leafNode.getClass());
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/SynchronousCallbackHandler.java:56]: Why do we know the `leafNode` is a `ClassTree` or `LambdaExpressionTree` here? (I assume at some point we are filtering out method references and the like?

Edit: Guess it has to do with where we call [updateEnvironmentMapping](https://github.com/uber/NullAway/blob/719b167ded3f65c4eb454d1909f436e9dd514076/nullaway/src/main/java/com/uber/nullaway/NullAway.java#L457). But by the time we get to [getNullnessInfoBeforeNewContext](https://github.com/uber/NullAway/blob/719b167ded3f65c4eb454d1909f436e9dd514076/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessAnalysis.java#L220) that's no longer very clear in our docs/checks.

File: nullaway/src/main/java/com/uber/nullaway/handlers/CompositeHandler.java (hunk 5 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/CompositeHandler.java:267]: See my comment above, I'm happy with making this change if you think it's better

File: nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java (hunk 7 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java:341]: Yes, that's exactly right.  This handler method is used to decide which access paths from the enclosure should be maintained when analyzing a lambda, beyond the standard ones (paths involving effectively-final locals).  Before I think we only used this for the `OptionalEmptinessHandler`

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java (hunk 6 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:179]: We are in fact missing coverage!  It turns out that #678 made the pseudo-field simulating contents of an `Optional` final, which means we already (safely) propagate nullability facts about that pseudo-field into lambdas, which means we no longer need this handler method!  I'll go ahead and delete this method in a separate PR.  Nice to have the test coverage exposed!

File: nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java]: 8a036763e0ee0239f6a8f7d6ffb1d9e1dcdb7925

File: nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/SyncLambdasTests.java:111]: 26bc3a06959bdcc6c3eaa012f8e9b761576b3c48

File: nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java:195]: Let me think through a bit more what it would take to implement the safer version.

File: nullaway/src/main/java/com/uber/nullaway/handlers/SynchronousCallbackHandler.java (hunk 8 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/SynchronousCallbackHandler.java:56]: Good point, tweaked the docs and method name in 34bb9f3909216a4b0109a21d3fa1066bae4eaad8

File: nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java:195]: @lazaroclapp I thought about this more and I think a reasonably precise safer version would be kind of a pain to implement.  My thought was to try to detect if the overall chain of stream calls ended in a terminal operation.  But there are a bunch of terminal operations on `Stream` itself, and then there are methods to convert `Stream` to `IntStream`, `DoubleStream`, etc., each with their own terminal operations.  (As an aside, in a follow-up we should probably handle those primitive stream types in the same way that we handle `Stream`s themselves.)  We could also just check if the enclosing method has a return type of `Stream`, but that is imprecise, and also misses cases like passing as a parameter or storing in a field.

Bottom line, my feeling is at this point, we are most likely ok going with the less safe version.  But, I think it's time we add a wiki page on our stream handling in general, documenting how we propagate nullability facts from `filter()` methods to subsequent callbacks and also this new propagation of nullability facts from the enclosing context.  On that page we could give caveats on cases where our handling could be unsound, and why we decided to do what we did.

Let me know what you think.

Comment (lazaroclapp) [reply nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java:195]: Of course, what this really needs is a new type system about the state of `Stream` objects... but in the absence of that, just eagerly propagating nullability of APs in the closure is probably safe enough (kidding about the `Stream` type-state system... mostly)

File: nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java (hunk 4 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java:206]: I guess it's not easy to have it in `Handler` and package visible... one other option is something like `AccessPathPredicates.java` in this same package, unless you feel this is very much linked to `CompositeHandler` in terms of its usage. Either way, I don't feel super strongly about it, if you want to leave it here it might be fine too.

**Review by lazaroclapp — APPROVED** [review]

File: nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java (hunk 4 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/BaseNoOpHandler.java:206]: You're right, creating an `AccessPathPredicates` class is better, I'll do that.

File: nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayStreamSupportPositiveCases.java:195]: To close the loop here I added a wiki page with some docs:

https://github.com/uber/NullAway/wiki/Stream-Handling
