### PR TITLE
Fix handling of static imports from subclasses

### LINKED ISSUE #764: Static methods can be accessed from within subclasses, but NullAway doesn't know this
The following is (annoyingly) valid Java code for calling a static method:

```
class Foo {
    public static String foo(@Nullable Object ignored) { return "Nonsense java black magic!"; };
}

class Bar extends Foo { }

class Main {
    public static void main(String[] args) {
        System.out.println(Bar.foo(null));
    }
}
```

However, NullAway will fail to read the annotations of `Foo.foo(...)` when inspecting the static call to `Bar.foo(...)` and thus give an error on `Bar.foo(null)`.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #764

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -400,29 +400,29 @@ public Description matchMethodInvocation(MethodInvocationTree tree, VisitorState
...
     // properly treat the method as unannotated, which is particularly important for equals()
     // methods.  This is an adaptation to a change in JDK 18; see
     // https://bugs.openjdk.org/browse/JDK-8272564
-    if (methodSymbol.owner.isInterface()) {
-      Symbol.MethodSymbol baseSymbol = (Symbol.MethodSymbol) methodSymbol.baseSymbol();
-      if (baseSymbol != methodSymbol && baseSymbol.owner == state.getSymtab().objectType.tsym) {
-        methodSymbol = baseSymbol;
-      }
-    }
-    return methodSymbol;
```
Comment (yuxincs) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:425]: question: I'm a bit confused about the previous code. It suggests that we actually want the `methodSymbol` and we only resolve to `baseSymbol` under certain conditions (i.e., interface method corresponding to one from `java.lang.Object`). But it seems with the updated code that we actually always want `baseSymbol`? 

Am I missing something?

**Review by yuxincs — APPROVED** [review]
Changes LGTM, but I have one clarifying question due to my unfamiliarity with the rest of the codebase.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:425]: Yes, that's a good question, this was due to my misunderstanding before.  Basically, always getting the base symbol is safe, since if there is no different base symbol the `baseSymbol()` method just returns `this`.  I didn't understand this before; more detail in [this comment](https://github.com/uber/NullAway/issues/764#issuecomment-1921863902).  In the next EP version the `getSymbol` overload for `MethodInvocationTree` will always call `baseSymbol()`, so in some cases it may get called twice, but that is fine.
