### PR TITLE
Better handling of method references passed to generic methods in JSpecify mode

### LINKED ISSUE #1431: JSpecify: Integrate method reference types with generic method type inference
Example:
```java
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;
import java.util.function.Function;
@NullMarked
class Test {
  interface Foo {
    default String get() {
      throw new RuntimeException();
    }
    default @Nullable String getNullable() {
      return null;
    }
  }
  private <T extends @Nullable Object> T create(Function<Foo, T> factory) {
    return factory.apply(new Foo() {});
  }
  void test() {
    String s1 = create(Foo::get);
    s1.hashCode(); // should be legal
    String s2 = create(Foo::getNullable);
    // BUG: Diagnostic contains: dereferenced expression s2 is @Nullable
    s2.hashCode();
  }
}
```

Generic method inference should infer that the first call to `create` returns a `@NonNull String` and the second call to `create` returns a `@Nullable String` based on the respective return types of `Foo#get` and `Foo#getNullable`.

### LINKED ISSUE #1474: JSpecify: bug with array contents annotations being copied by `javac`
Example:
```java
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;
@NullMarked
class Test {
  interface Consumer<T extends @Nullable Object> {
    void accept(T thing);
  }
  static class Util {
    static void take(String... thing) {
    }
    static void takeNullable(String @Nullable... thing) {
    }
    static void takeNullableArgs(@Nullable String... thing) {
    }
  }
  private <V extends @Nullable Object> void consume(Consumer<V> consumer, V value) {
    consumer.accept(value);
  }
  void testConsume(@Nullable String [] sNullableContents) {
    // should be illegal!
    consume(Util::take, sNullableContents);
    // should be illegal!
    consume(Util::takeNullable, sNullableContents);
  }
}
```
For both the `consume` calls, we end up passing in an array containing `@Nullable String`s to a function expecting an array containing `@NonNull String`s, which we should reject.  I think the missed warning is because `javac` infers the type `Consumer<@Nullable String[]>` for the method references at the call sites, copying over the annotation from the other argument.  NullAway needs to "undo" that annotation when it does its inference.  This is vaguely related to #1453, but a different issue that seems specific to arrays.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1431 
Fixes #1474 

We make two key changes.  First, we store the inferred types of method reference expressions in the `inferredPolyExpressionTypes` cache, similar to what we did for lambdas, so that some later checks that require the type of the method reference get the inferred type.

Second, when a method reference is passed to a generic method, sometimes the type for the method reference computed by `javac` does not include nullability annotations on nested types (see #1474 and a new test case here).  So, we need to do explicit checks using the return and parameter types of the referenced method, to see if nested nullability annotations are consistent with the target functional-interface method type.

For code reuse and clarity, we extract a utility method for doing type checks related to method references to a new class `GenericsUtils`, and rewrite one use of the original logic to use the new utility.

## Summary by CodeRabbit

* **New Features**
  * Added nullability checks for method references when used with generic type inference.

* **Improvements**
  * Brought method-reference type handling in line with lambda expressions, improving detection of parameter and return nullability mismatches, including varargs and explicit type-argument scenarios.

* **Tests**
  * Added tests covering method-reference interactions with generic inference and expected nullability diagnostics.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 1]
```diff
@@ -1217,9 +1150,22 @@ private void handleMethodRefInGenericMethodInference(
...
       }
     }
-    if (overridingMethod.asType() instanceof Type.ForAll) {
-      // the referenced method is a generic method; we need to substitute inferred nullability for
-      // type arguments if it was inferred
+    List<? extends ExpressionTree> typeArgumentTrees = memberReferenceTree.getTypeArguments();
+    if (typeArgumentTrees != null
+        && !typeArgumentTrees.isEmpty()
+        && overridingMethod.asType() instanceof Type.ForAll forAllType) {
+      // handle explicit type arguments in method reference, e.g., x::<Foo>method
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1161]: The other changes in this PR exposed this issue; apparently we weren't doing the appropriate substitution before when a method reference has explicit type arguments

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java [hunk 2]
```diff
@@ -417,6 +417,148 @@ void test() {
...
+                takeMultiple(Test::takeNonNull, Test::takeNonNull, c);
+              }
+              static void takeNonNullNested(Foo<String> f) {}
+              static void takeNullableNested(Foo<@Nullable String> f) {}
+              void testNegative2(Foo<String> f1, Foo<@Nullable String> f2) {
+                takeMultiple(Test::takeNonNullNested, Test::takeNonNullNested, f1);
+                takeMultiple(Test::takeNullableNested, Test::takeNullableNested, f2);
+              }
+              void testPositive2(Foo<String> f1) {
+                // BUG: Diagnostic contains: parameter type of referenced method is Test.Foo<@Nullable String>, but parameter in functional interface method has type Test.@NonNull Foo<String>
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java]: Why `Test.@NonNull Foo<String>`? Shouldn't it be inferring `Test.Foo<@NonNull  String>`? Guess technically those types are one and the same, but it's still a confusing error...

Maybe:

```
// BUG: Diagnostic contains: parameter type of referenced method is Test.Foo<@Nullable String>, but parameter in functional interface method has type Test.Foo<String>
```

Is what we'd expect / want?

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java [hunk 3]
```diff
@@ -417,6 +417,148 @@ void test() {
...
+                return s1.get();
+              }
+              static Foo<String> makeNonNullNested() {
+                throw new RuntimeException();
+              }
+              static Foo<@Nullable String> makeNullableNested() {
+                throw new RuntimeException();
+              }
+              void testPositive(Foo<String> f1) {
+                // BUG: Diagnostic contains: referenced method returns Test.Foo<@Nullable String>, but functional interface method returns Test.@NonNull Foo<String>
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java]: Same question as above

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsUtils.java [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+
+    // first, figure out the proper method type to use for the member reference
+    Symbol.MethodSymbol referencedMethod = ASTHelpers.getSymbol(memberReferenceTree);
+    if (referencedMethod == null || referencedMethod.isConstructor()) {
+      // TODO handle constructor references like Foo::new;
+      //  https://github.com/uber/NullAway/issues/1468
+      return;
+    }
+    Type.MethodType referencedMethodType =
+        castToNonNull(
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsUtils.java]: Why is this cast safe? And why is it preferred to an if check and `return`? I suspect it might be both, just noting that it might benefit from a comment as to why :)

Edit: There was a null check and an alternative default for `referencedMethodType` in the non-refactored version, no?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 5]
```diff
@@ -122,7 +123,7 @@ private static final class InferenceFailure implements MethodInferenceResult {
   }
 
   private final NullAway analysis;
-  private final Config config;
+  /* package-private */ final Config config;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Why? Can't get pass it around or create a package-private accessor?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 6]
```diff
@@ -1071,120 +1110,14 @@ private void handleMethodRefInGenericMethodInference(
...
-      return;
-    }
-    // javac resolved this member reference using varargs (variable-arity) adaptation.
-    // Use the element type from the referenced varargs array type
-    Type varargsElementType = types.elemtype(varargsArrayType);
-    for (int i = varargsParamPosition; i < fiParamCount; i++) {
-      solver.addSubtypeConstraint(fiParamTypes.get(fiStartIndex + i), varargsElementType, false);
-    }
+        state,
+        (subtype, supertype, relationKind) -> {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: I guess `relationKind` is used only for reporting and then only when checking call-sites, right?

Does java support something like: `(subtype, supertype, _) -> {` here for clarity?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 1 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1161]: Is there a case where a method reference has some type arguments given explicitly and some inferred? (Not sure if this is possible in Java, just checking)

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 7]
```diff
@@ -1648,9 +1594,32 @@ public void compareGenericTypeParameterNullabilityForCall(
                 return;
               }
 
+              if (currentActualParam instanceof MemberReferenceTree memberReferenceTree) {
+                // the type of the method reference tree provided by javac may not capture
+                // nullability of nested types.  so, do explicit type checks based on the return and
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]:
```suggestion
                // nullability of nested types. So, do explicit type checks based on the return and
```

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java]: You have a good point.  This is exposing some implementation details of inference; we add explicit `@NonNull` annotations to certain types to work around quirks of `javac`.  But that shouldn't be reflected in the error message printing.

Do you think we should just never print `@NonNull` annotations in error messages?  That would be consistent with JSpecify defaulting.  Because of the workarounds mentioned above, it may be hard to tell when a `@NonNull` was inserted by our code vs when it was present in the original code (as a restrictive annotation), but I think it might be best just to never print them.

Also, would you like the error message fix done as part of this PR?  I could also do it in a separate PR, and land that one before or after the changes here.

Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java]: See https://github.com/uber/NullAway/pull/1507 for a PR that would strip `@NonNull` annotations from types in error messages.

Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodLambdaOrMethodRefArgTests.java]: This is fixed now after merging in #1507

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsUtils.java (hunk 4 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsUtils.java]: You're right.  A null check does no harm here (though I don't think we should ever see null).  Will add.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 5 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Good catch, added a package-private getter

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 6 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java]: Java does support `_` but only in a more recent version than we are using.  I renamed to `unused` here; you're right this is only used in the other case for error reporting.

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:1161]: No, it either needs to be all explicit or all inferred
