### PR TITLE
Resolve regression for type annotations directly on inner types.

### LINKED ISSUE #705: [0.10.6] @Nullable ignored and warns as non-null field
This is easily resolved by adding the suppression, but it appears to be a regression unless I am doing something wrong?

```console
> Task :guava:compileJava
/Users/ben/projects/caffeine/guava/src/main/java/com/github/benmanes/caffeine/guava/CaffeinatedGuavaCache.java:156:
warning: [NullAway] @NonNull field CaffeinatedGuavaCache$AsMapView.entrySet not initialized
    @Nullable EntrySetView entrySet;
                           ^
    (see http://t.uber.com/nullaway )
  Did you mean '@SuppressWarnings("NullAway.Init") @Nullable EntrySetView entrySet;'?
/Users/ben/projects/caffeine/guava/src/main/java/com/github/benmanes/caffeine/guava/CaffeinatedGuavaCache.java:157:
warning: [NullAway] @NonNull field CaffeinatedGuavaCache$AsMapView.keySet not initialized
    @Nullable KeySetView keySet;
                         ^
    (see http://t.uber.com/nullaway )
  Did you mean '@SuppressWarnings("NullAway.Init") @Nullable KeySetView keySet;'?
/Users/ben/projects/caffeine/guava/src/main/java/com/github/benmanes/caffeine/guava/CaffeinatedGuavaCache.java:158:
warning: [NullAway] @NonNull field CaffeinatedGuavaCache$AsMapView.values not initialized
    @Nullable ValuesView values;
                         ^
    (see http://t.uber.com/nullaway )
  Did you mean '@SuppressWarnings("NullAway.Init") @Nullable ValuesView values;'?
3 warnings
```

### PR DESCRIPTION
**Pull request by lazaroclapp**
This resolves #705 by broadening our slightly overzealous filtering from #702.

We still want to filter type use annotations out when they happen on arrays, wildcards, or
type parameters. However, we can handle annotations on inner types (i.e. `Foo.@Nullable Bar`).
More importantly, these inner types appear implicitly in natural code involving inner classes,
such as:

```
class Bar {
   @Nullable Foo foo; // <- this is, implicitly Bar.@Nullable Foo !!
   class Foo { }
}
```

Not handling this case leads to confusing an unintuitive errors where a `@Nullable` annotation
with a type use location will seemingly stop working for certain fields at random, if those fields
are of an inner type.

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java [hunk 1]
```diff
@@ -990,4 +990,90 @@ public void annotationAppliedToTypeParameter() {
...
+  @Test
+  public void annotationAppliedToInnerTypeExplicitly() {
+    defaultCompilationHelper
+        .addSourceLines(
+            "Test.java",
+            "package com.uber;",
+            "import org.checkerframework.checker.nullness.qual.Nullable;",
+            "class Test {",
+            "  Test.@Nullable Foo f1;",
+            "  @Nullable Test.Foo f2;",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:1021]: Is it a problem that we treat these two as strictly equivalent for now? Feels like we need to, in order to support the `annotationAppliedToInnerTypeImplicitly` case.

File: nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java [hunk 2]
```diff
@@ -990,4 +990,90 @@ public void annotationAppliedToTypeParameter() {
...
+            "class Bar {",
+            "  public class Foo { }",
+            "}")
+        .addSourceLines(
+            "Test.java",
+            "package com.uber;",
+            "import org.checkerframework.checker.nullness.qual.Nullable;",
+            "class Test {",
+            "  Bar.@Nullable Foo f1;",
+            "  @Nullable Bar.Foo f2;",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:1049]: Here we could potentially filter the first case, by only allowing inner types if the outer types match the containing scope, but it seems like extra brittleness and I am not sure supporting this is incorrect. Is there a difference in semantics here between the two cases above according to JSpecify or anything else?

Comment (lazaroclapp) [reply nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:1049]: Actually, Error Prone does seem to care about this:

```
error: [NullableOnContainingClass] Type-use nullability annotations should annotate the inner class, not the outer class (e.g., write `A.@Nullable B` instead of `@Nullable A.B`).
```

Which is annoying, because many devs see the annotation as going on the field, not the type, whether or not it is a type use annotation. So they would write:

```
@Nullable
Bar.Foo f2;
```

and get an error from that checker.

Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:1049]: Still need to look at the whole PR, but yes, according to the spec, type-use annotations should go on the inner type:

https://jspecify.dev/docs/user-guide#type-use-annotation-syntax

We'll have to help developers adjust to this with good error messages.

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java [hunk 3]
```diff
@@ -292,7 +293,10 @@ private static boolean isDirectTypeUseAnnotation(Attribute.TypeCompound t) {
     // location is a list of TypePathEntry objects, indicating whether the annotation is
     // on an array, inner type, wildcard, or type argument. If it's empty, then the
     // annotation is directly on the type.
-    return t.position.location.isEmpty();
+    // We care about both annotations directly on the outer type and also those on directly
+    // on an inner type, but wish to discard annotations on arrays, wildcards, or type arguments.
+    return t.position.location.stream()
+        .allMatch(l -> l.tag.equals(TypeAnnotationPosition.TypePathEntryKind.INNER_TYPE));
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:299]: Why do we need `allMatch` here?  Don't we want to check that there _exists_ an element of the list with tag `INNER_TYPE` such that it is on the "innermost" type?  E.g., what if we have field declaration `A.@Nullable B.C foo;`; do we want to treat that as a `@Nullable` reference?

Also we may have a type like `A.@Nullable B<@Nullable C>`.  I think we should treat this as as a `@Nullable` reference, but `allMatch` may be too strict?  I'm not sure if we'll get a single `TypeCompound` in two different locations for that case...

File: nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:1021]: I think we have to treat them equivalently for now.  The former is a correct usage of the annotation, and the latter we must allow for backward compatibility.  Do we know why Error Prone complains about the case below but not this one?

**Review by msridhar — COMMENTED** [review]
One possible concern

**Comment by msridhar** [comment]
Oof, this is a bit worse than we thought, see the test in f300953.  Right now we report an error for the `@Nullable Object[] foo = null;` line, since that `@Nullable` annotation has a location of `ARRAY` kind (i.e., it is saying that the _elements_ of the array are `@Nullable` according to the spec).  To say that the field itself is `@Nullable` you have to write `Object @Nullable[] foo2 = null;`.

Again for backward compatibility I _think_ we want to treat _both_ positions as making the field `@Nullable` for now.  It feels weird to only accept the "wrong" version, but I guess we could do that also.  WDYT @lazaroclapp?

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:299]: Upon further investigation, I _think_ `location` only has length greater than 1 for multi-dimensional arrays.  For a type like `A.@Nullable B<@Nullable C>` we will get two different `TypeCompound` objects each of whose `position.location` lists will be length 1.

Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:299]: We do need `allMatch`, because `A.B<@Nullable C>` shows as having the location array `["INNER_TYPE", "TYPE_ARGUMENT(0)"]`.

Think of it like a path: "annotation found at the type argument, position 0, of the inner type".

This is needed, because otherwise stuff like `A<@Bar E>.B<C>.` would be ambiguous if `@Bar` just says `["TYPE_ARGUMENT(0)"]`.

So, in your example above, if we see `A.@Nullable B<@Nullable C>`, what we get is two `@Nullable` annotations (two calls to `getTypeUseAnnotations`) one which has the location array  `["INNER_TYPE", "TYPE_ARGUMENT(0)"]` (the one by `C`) and one which has location array `["INNER_TYPE"]`. We want to match only the second.

We want to match "a path including only a chain of inner types" and that's `allMatch`.

**Comment by lazaroclapp** [comment]
> Oof, this is a bit worse than we thought, see the test in [f300953](https://github.com/uber/NullAway/commit/f3009530c566e2877d49ae4fbe7291083cf6c946). Right now we report an error for the `@Nullable Object[] foo = null;` line, since that `@Nullable` annotation has a location of `ARRAY` kind (i.e., it is saying that the _elements_ of the array are `@Nullable` according to the spec). To say that the field itself is `@Nullable` you have to write `Object @Nullable[] foo2 = null;`.
> 
> Again for backward compatibility I _think_ we want to treat _both_ positions as making the field `@Nullable` for now. It feels weird to only accept the "wrong" version, but I guess we could do that also. WDYT @lazaroclapp?

We specifically don't have JSpecify-like semantics for arrays yet, do we? I think this is an orthogonal concern to the purpose of this PR, but happy to have the test there if we currently handle the "correct" case. I think whenever we support the nullability of _elements_ of arrays, that will be a major breaking change either way, since we always used the opposite semantics here from JSpecify.

**Comment by msridhar** [comment]
Let me try to summarize the overall situation here so we can think about potential solutions and their tradeoffs.  #702 addressed an issue where `List<@Nullable String> list` got treated as if `list` itself was `@Nullable`, due to the type use annotation on the type argument (identified in https://github.com/uber/NullAway/issues/674#issuecomment-1363205545).  The change there was to only consider a type-use `@Nullable` annotation to be relevant a field / parameter / return type if the annotation was _not_ in an array, inner type, wildcard, or type argument position.

Unfortunately, this change was bad for a couple of reasons:

1. As shown in #705, sometimes type use annotations are in an inner type position even when it doesn't syntactically look like it (see example in https://github.com/uber/NullAway/issues/705#issuecomment-1368082909).
2. Syntactically, the "correct" location for a type use annotation is not what NullAway users (who mostly use declaration annotations) are used to.  Relevant discussion is in the [JSpecify user guide](https://jspecify.dev/docs/user-guide#type-use-annotation-syntax).  The change in #702 unintentionally broke cases where users used a type use annotation (like the Checker Framework or JSpecify `@Nullable`) and wrote `@Nullable Map.Entry foo1 = null;` or `@Nullable Object[] foo2 = null;`, as it changed NullAway to only look for the annotations in the syntactically-correct place (i.e., `Map.@Nullable Entry foo1` or `Object @Nullable [] foo2`).

For inner types, I think I'm fine with the solution currently implemented in this PR.  It fixes point 1 above and gets rid of the surprising change in checking behavior for inner types from point 2.  It does lead to a bit of weirdness, as shown in here:

https://github.com/uber/NullAway/blob/1b1a5b1008612606a36062a99e7f5e21eb704680/nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java#L1113-L1117

In particular, writing `A.@Nullable B.C foo2` makes `foo2` `@Nullable`.  But this seems like a corner case that shouldn't affect users much right now.

Dealing with arrays is a bit more complicated, since users may want to write annotations to express the nullability of array contents.  If we adopt a solution like the one used in this PR for inner types, writing either `@Nullable Object[] foo` or `Object @Nullable[] foo` would make `foo` `@Nullable`.  But, this would mean that if `foo` were intended to be a `@NonNull` array reference containing `@Nullable Object`s, a user could not write the correct annotation for this case (`@Nullable Object[] foo`) without adverse impacts from NullAway (since `foo` itself would then be treated as `@Nullable`).  Such NullAway users would be forced to either not write the correct annotations for the nullability of array contents for now or to deal with references becoming unintentionally `@Nullable` (the latter seems worse).  A similar issue is seen in #674 for varargs arrays.  While this downside is unfortunate, it does match the behavior of NullAway before #702 landed.

We could also just stick with requiring users to write type use nullability annotations for arrays in the right spot.  But that kind of breaking change seems weird to introduce by accident, and I'm not sure of other unintended consequences.  That seems like a change we should introduce deliberately and possibly behind a flag at first to let users adopt gradually.

So, I think our best option is to handle inner type and array type use annotations in the same way for now, as inner types are currently being handled in this PR.  I'm not sure about a combination of these, e.g., `A.B.@Nullable C [][] foo = null;`.  This annotation does not make `foo` `@Nullable` under proper usage of type use annotations nor in a backward compatibility scenario.  So I guess we can just treat `foo` as `@NonNull` for this case?

Ok, those are all my thoughts for now.  It's a messy situation but it's good that we are at least understanding the scope of the issue finally.

**Comment by lazaroclapp** [comment]
Just as a note:

> 2\. The change in [Fix logic for @Nullable annotation on type parameter #702](https://github.com/uber/NullAway/pull/702) unintentionally broke cases where users used a type use annotation (like the Checker Framework or JSpecify `@Nullable`) and wrote `@Nullable Map.Entry foo1 = null;` [...] , as it changed NullAway to only look for the annotations in the syntactically-correct place.

I don't think this is true (see the original test case). The change is only for arrays, because we are explicitly excluding arrays as a location, but it would be fine when annotating the outermost type, because that's just the location path `[]`.

> I'm not sure about a combination of these, e.g., `A.B.@Nullable C [][] foo = null;`. This annotation does not make foo `@Nullable` under proper usage of type use annotations nor in a backward compatibility scenario. So I guess we can just treat foo as `@NonNull` for this case?

We could. This could be as easy as requiring that either all components of the location are inner types or all components of the location are arrays, but not a mix of both. There is an annoying edgecase where:

```
class Test {
  Test.@Nullable Foo[][] fs;
  class Foo { }
}
```

given explicitly does produce path `[ARRAY, ARRAY, INNER_TYPE]` for `fs`.

But:

```
class Test {
  @Nullable Foo[][] fs;
  class Foo { }
}
```

shows up as just `[ARRAY, ARRAY]` (which means we would allow it with our backward compatibility considerations).

Maybe the later is fine from the point of view of developer ergonomics? It's still a bit confusing, though...

**Comment by msridhar** [comment]
> > 2. The change in [Fix logic for @Nullable annotation on type parameter #702](https://github.com/uber/NullAway/pull/702) unintentionally broke cases where users used a type use annotation (like the Checker Framework or JSpecify `@Nullable`) and wrote `@Nullable Map.Entry foo1 = null;` [...] , as it changed NullAway to only look for the annotations in the syntactically-correct place.
> 
> I don't think this is true (see the original test case). The change is only for arrays, because we are explicitly excluding arrays as a location, but it would be fine when annotating the outermost type, because that's just the location path `[]`.

Yes I think you're right; my mistake.
> 
> > I'm not sure about a combination of these, e.g., `A.B.@Nullable C [][] foo = null;`. This annotation does not make foo `@Nullable` under proper usage of type use annotations nor in a backward compatibility scenario. So I guess we can just treat foo as `@NonNull` for this case?
> 
> We could. This could be as easy as requiring that either all components of the location are inner types or all components of the location are arrays, but not a mix of both. There is an annoying edgecase where:
> 
> ```
> class Test {
>   Test.@Nullable Foo[][] fs;
>   class Foo { }
> }
> ```
> 
> given explicitly does produce path `[ARRAY, ARRAY, INNER_TYPE]` for `fs`.
> 
> But:
> 
> ```
> class Test {
>   @Nullable Foo[][] fs;
>   class Foo { }
> }
> ```
> 
> shows up as just `[ARRAY, ARRAY]` (which means we would allow it with our backward compatibility considerations).
> 
> Maybe the later is fine from the point of view of developer ergonomics? It's still a bit confusing, though...

Everything we do here is going to be confusing for a while 🙂 I think allowing for all inner types or all arrays is probably the best thing to do for now.

File: nullaway/src/test/java/com/uber/nullaway/NullAwayTypeUseAnnotationsTests.java [hunk 4]
```diff
@@ -0,0 +1,221 @@
...
+  public void typeUseAnnotationOnInnerMultiLevel() {
+    defaultCompilationHelper
+        .addSourceLines(
+            "Test.java",
+            "package com.uber;",
+            "import java.util.Set;",
+            "import org.checkerframework.checker.nullness.qual.Nullable;",
+            "class A { class B { class C {} } }",
+            "class Test {",
+            "  // At some point, we should not treat foo1, foo2, or foo4 as @Nullable.",
```
Comment (msridhar) [inline nullaway/src/test/java/com/uber/nullaway/NullAwayTypeUseAnnotationsTests.java:207]: Just `foo1` or `foo2`?  Looks like `foo4` is now not treated as `@Nullable`.

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java [hunk 5]
```diff
@@ -292,7 +296,35 @@ private static boolean isDirectTypeUseAnnotation(Attribute.TypeCompound t) {
...
+    // For arrays, we treat annotations on the outer type and on any dimension of the array
+    // as applying to the nullability of the array itself, not the elements.
+    // We don't allow mixing of inner types and array dimensions in the same location
+    // (i.e. `Foo.@Nullable Bar []` is meaningless).
+    // These aren't correct semantics for type use annotations, but a series of hacky
+    // compromises to keep some semblance of backwards compatibility until we can do a
+    // proper deprecation of the incorrect behaviors for type use annotations when their
+    // semantics don't match those of a declaration annotation in the same position.
+    // See https://github.com/uber/NullAway/issues/708
+    boolean location_has_inner_types = false;
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:311]: Stick with standard lowerCamelCase?
```suggestion
    boolean locationHasInnerTypes = false;
```

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java [hunk 6]
```diff
@@ -292,7 +296,35 @@ private static boolean isDirectTypeUseAnnotation(Attribute.TypeCompound t) {
...
+    boolean location_has_array = false;
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:312]: Similarly:
```suggestion
    boolean locationHasArray = false;
```

**Review by msridhar — APPROVED** [review]
Mostly LGTM!  Approved assuming minor comments below are addressed

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java (hunk 5 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:311]: Ugh, sorry, the perils of alt-tabbing between Python and Java code 😅
