### PR TITLE
JSpecify: handle intersection type in one place

### LINKED ISSUE #1013: JSpecify: Another "Did not find supertype" crash, with Strings
> @SolomonSun2010 Do you have an example input program that causes the error? Without that it'll be hard to track down the problem.

@msridhar OK，when running NullAway， normally display :
warning: [NullAway] xxxxxx

**Suddenly, error message is:**

An unhandled exception was thrown by Error Prone static analysis pluging.
", relativeServices=" + (relativeServices == null ? "relativeServices == null" : relativeServices.size())

```java
    @Override
    public String toString() {
        return "ServiceExtraInfo{" +
            "appInfoData=" + (appInfoData == null ?  "null" : appInfoData.toString()) +
            ", relativeServices=" + (relativeServices == null ? "relativeServices == null" : relativeServices.size())
            + getRelativeServicesToString() + '}';
    }
```

_Originally posted by @SolomonSun2010 in https://github.com/uber/NullAway/issues/1008#issuecomment-2270762307_

### PR DESCRIPTION
**Pull request by msridhar**
Intersection types may arise, e.g., as part of string concatenation.  We handling of an intersection type for one scenario; broader handling definitely requires more testing and thinking.

Fixes #1013

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericsTests.java [hunk 1]
```diff
@@ -1856,6 +1856,52 @@ public void issue1008() {
...
+            "import org.jspecify.annotations.Nullable;",
+            "import java.io.Serializable;",
+            "public class Test {",
+            "  interface A<T extends @Nullable Object> {}",
+            "  static class B implements A<@Nullable String>, Serializable {}",
+            "  static void test1(Object o) {",
+            "    var x = (A<String> & Serializable) o;",
+            "    // BUG: Diagnostic contains: Cannot assign from type B to type A<String> & Serializable",
+            "    x = new B();",
+            "  }",
```
Comment (lazaroclapp) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericsTests.java:1893]: To be clear, the case where we have:

```
            "    var x = (A<@Nullable String> & Serializable) o;",
            "    x = new B();",
```

Should have no error, right? Should we encode that test case just to make sure we never regress that?

**Review by lazaroclapp — APPROVED** [review]
LGTM, minimal tests nit, we might want the corresponding `testNegative1` and `testNegative2` cases, assuming I understand what intersection types do correctly.

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericsTests.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericsTests.java:1893]: you're right, and i think we will get a false positive on that test for now (since for some reason `var`-declared variables don't get types with all the right annotations).  i'll add tests and open an issue for outstanding tasks, but will fix in a subsequent PR

Comment (msridhar) [reply nullaway/src/test/java/com/uber/nullaway/jspecify/GenericsTests.java:1896]: Addressed in 5a8bdd6393f0d6b2c54801b420dccdb46bd72b17 along with link to issue https://github.com/uber/NullAway/issues/1022
