### PR TITLE
Treat parameter of generated Record.equals() methods as @Nullable

### LINKED ISSUE #619: false-positive trigger on java17record.equals(null)
- [X] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.

```java
class A {
    void test() {
        record Foo() {};
        new Foo().equals(null);
    }
}
```
trips with
>  error: [NullAway] passing @Nullable parameter 'null' where @NonNull is required
    new Foo().equals(null);
    
But equals to null on java17 records does work without producing NPE.

  - [X] Please include the library version number, including the minor and patch version, in the issue text.
0.9.8

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #619

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/Nullness.java [hunk 1]
```diff
@@ -210,10 +212,34 @@ public static boolean hasNullableAnnotation(Symbol symbol, Config config) {
...
+    // the generated implementation handles null (as required by the contract of Object.equals())
+    if (isRecordEqualsParam(symbol, paramInd)) {
+      return true;
+    }
     return hasNullableAnnotation(
         NullabilityUtil.getAllAnnotationsForParameter(symbol, paramInd), config);
   }
 
+  private static boolean isRecordEqualsParam(Symbol.MethodSymbol symbol, int paramInd) {
+    if (!symbol.owner.getKind().toString().equals("RECORD")) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/Nullness.java:225]: We need `toString()` here (vs an enum equality check of some sort) for older JDK compat, right? Maybe worth a quick comment if so?

**Review by lazaroclapp — APPROVED** [review]
Makes sense 🙂 Quick question and possible documentation nit.
