### PR TITLE
Address severe performance regression in dataflow analysis

### LINKED ISSUE #1327: NullAway 0.12.11 much slower than previous versions
I've found that compared to previous versions, NullAway 0.12.11 is 2-4 times slower, and now takes more time than javac itself.

Compiling a large project we have takes:
* 11s with no checks (-XepDisableAllChecks)
* 18s with NullAway 0.12.10
* 39s with NullAway 0.12.11

I found that most time is spent in `org.checkerframework.nullaway.dataflow.analysis.ForwardAnalysisImpl.performAnalysis`, which used to be called only once per method but now is called on every dereference. Since this is a whole-method analysis, the overall time to check a method is O(n^2) in its size.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1327 (I hope)

#1309 introduced a severe performance regression in dataflow analysis, as the result of running the dataflow analysis was no longer being cached.  This caused a >100X slowdown in our dataflow micro-benchmark!  (Which we really should have measured before landing #1309...)

This PR re-introduces the cache for analysis results (by tracking when we have already run the analysis).  This fix exposed some other bugs in generic method inference where we weren't passing around the right `TreePath` to enable discovery of appropriate assignment contexts and containing methods; we fix those bugs here too.

## Summary by CodeRabbit

* **New Features**
  * More precise nullness inference for generic method returns in JSpecify mode by using invocation context when available.

* **Bug Fixes**
  * Prevents redundant dataflow analyses by tracking already-run analyses; cache invalidation resets this tracking.
  * Behavior changes are internal only; public API remains unchanged.

* **Tests**
  * Updated test setup and expected diagnostics to reflect refined generic inference and nullability behavior.

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java [hunk 1]
```diff
@@ -1299,7 +1299,7 @@ public void inferenceFromDataflow() {
             "    // to ensure that dataflow runs",
             "    Object x = new Object(); x.toString();",
             "    Object y = null;",
-            "    // BUG: Diagnostic contains: returning @Nullable expression from method with @NonNull return type",
+            "    // BUG: Diagnostic contains: passing @Nullable parameter 'y' where @NonNull is required",
```
Comment (msridhar) [inline nullaway/src/test/java/com/uber/nullaway/jspecify/GenericMethodTests.java:1302]: This error message now makes sense at least if you know NullAway internals.  Inference for the `id(y)` call fails, so we fall back on treating its parameter and return types as non-null.  So, we get an error that we can't pass in `y`.

**Review by yuxincs — APPROVED** [review]

**Comment by jeffrey-easyesi** [comment]
Yes - I've confirmed compiling our code with this branch takes about the same time as 0.12.10, and still has the same output as 0.12.11.
