### PR TITLE
fix #676 Fix a NPE using CheckOptionalEmptiness=true (second option)

### LINKED ISSUE #676: NPE within NullAway using 'CheckOptionalEmptiness=true'
This bug occurs when using `CheckOptionalEmptiness` in combination with `Optional.ofNullable(map.get(KEY))` followed in some way by a method reference (e.g. `Map.Entry::getKey`). The failure is due to the `OptionalEmptinessHandler` `OPTIONAL_CONTENT` VariableElement returning null for all methods unexpectedly, including `VariableElement::getKind`. There are a few ways we could prevent future regressions, but that discussion may work better in a PR than this ticket.

I have a test which reproduces the failure, which I will add in a PR once I have an issue number from this report.

Environment: error-prone 2.15.0, nullaway 2.10.2. Reproducible using Java 11 and 17

```
An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: unknown version
     BugPattern: NullAway
     Stack Trace:
     java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.ElementKind.equals(Object)" because the return value of "javax.lang.model.element.Element.getKind()" is null
  	at com.uber.nullaway.handlers.StreamNullabilityPropagator.onMatchMethodReference(StreamNullabilityPropagator.java:352)
  	at com.uber.nullaway.handlers.CompositeHandler.onMatchMethodReference(CompositeHandler.java:103)
  	at com.uber.nullaway.NullAway.matchMemberReference(NullAway.java:865)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberReference(ErrorProneScanner.java:715)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberReference(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMemberReference.accept(JCTree.java:2546)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
```

Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [X] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.

  - [X] Please include the library version number, including the minor and patch version, in the issue text.

### PR DESCRIPTION
**Pull request by carterkozak**
See #677 and #676

This PR takes a more involved path, filling out the `VariableElement` implementation used within `OptionalEmptinessHandler` to avoid the same class of issue in the future.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java [hunk 1]
```diff
@@ -230,78 +246,97 @@ private boolean optionalIsGetCall(Symbol.MethodSymbol symbol, Types types) {
...
+      return elementVisitor.visitVariable(this, p);
+    }
 
-      @Override
-      @Nullable
-      public Set<Modifier> getModifiers() {
-        return null;
-      }
+    @Override
+    @Nullable
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:322]: Should this `@Nullable` be removed?

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java [hunk 2]
```diff
@@ -230,78 +246,97 @@ private boolean optionalIsGetCall(Symbol.MethodSymbol symbol, Types types) {
...
-      public List<? extends AnnotationMirror> getAnnotationMirrors() {
-        return null;
-      }
+    @Override
+    @Nullable
+    public Element getEnclosingElement() {
+      // A field would have an enclosing element, however this method isn't guaranteed to
+      // return non-null in all cases. It may be beneficial to implement this in a future
+      // improvement.
+      return null;
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:290]: This could be tricky to implement actually, since we support multiple `Optional` types (Java's and Guava's, e.g.).  If you agree, maybe we could mention that as the reason we return `null`?

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java [hunk 3]
```diff
@@ -230,78 +246,97 @@ private boolean optionalIsGetCall(Symbol.MethodSymbol symbol, Types types) {
    * A {@link VariableElement} for a dummy "field" holding the contents of an Optional object, used
    * in dataflow analysis to track whether the Optional content is present.
    */
-  private static VariableElement getOptionalContentElement() {
-    return new VariableElement() {
-      @Override
-      @Nullable
-      public Object getConstantValue() {
-        return null;
+  private static final class OptionalContentVariableElement implements VariableElement {
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:249]: Can we add a bit of Javadoc on this class?

**Review by msridhar — COMMENTED** [review]
I like this approach much more than the other one!  Let's go with this version.  Just a couple of minor comments / questions

**Comment by msridhar** [comment]
Also if you could merge latest `master` branch or rebase that'd be great

File: nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java (hunk 3 above)
Comment (carterkozak) [reply nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:249]: Sure thing, I kept the javadoc from the `getOptionalContentElement()` factory function which applies to the type, but I should describe that these should be requested from a context rather than instantiated directly.

Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/OptionalEmptinessHandler.java:249]: Ah I missed that the previous Javadoc was still there, sorry

**Review by msridhar — APPROVED** [review]
Thanks again for the fix!

**Comment by carterkozak** [comment]
My pleasure, thanks for the review!
