### PR TITLE
Fix crash with switch expression as a lambda body

### LINKED ISSUE #524: Crash with lambda combined with a switch expression
Test case:
```java
  @Test
  public void testSwitchExprLambda() {
    defaultCompilationHelper
        .addSourceLines(
            "SwitchExpr.java",
            "package com.uber;",
            "import java.util.function.Function;",
            "class SwitchExpr {",
            "  int i;",
            "  public void testSwitchExprLambda() {",
            "    Function<SwitchExpr,Object> f = (s) -> switch (s.i) { case 3, 4, 5 -> new Object(); default -> \"hello\"; };",
            "  }",
            "}")
        .doTest();
  }
```

Gives us a crash:
```
  Caused by: java.lang.AssertionError: case visitor is implemented in SwitchBuilder
  	at org.checkerframework.nullaway.dataflow.cfg.builder.CFGTranslationPhaseOne.visitCase(CFGTranslationPhaseOne.java:2407)
  	at org.checkerframework.nullaway.dataflow.cfg.builder.CFGTranslationPhaseOne.visitCase(CFGTranslationPhaseOne.java:193)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1357)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at org.checkerframework.nullaway.dataflow.cfg.builder.CFGTranslationPhaseOne.scan(CFGTranslationPhaseOne.java:491)
  	at org.checkerframework.nullaway.dataflow.cfg.builder.CFGTranslationPhaseOne.scan(CFGTranslationPhaseOne.java:193)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
```

Reported in https://github.com/uber/NullAway/issues/289#issuecomment-999757311 by @lessthanoptimal.  Looks like an issue with Checker Framework; will report upstream.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #524 

Fixed by bumping Checker Framework version

### CODE REVIEW

File: jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwaySwitchTests.java [hunk 1]
```diff
@@ -156,4 +156,20 @@ public void testSwitchExprUnbox() {
...
+  public void testSwitchExprLambda() {
+    defaultCompilationHelper
+        .addSourceLines(
+            "SwitchExpr.java",
+            "package com.uber;",
+            "import java.util.function.Function;",
+            "class SwitchExpr {",
+            "  int i;",
+            "  public void testSwitchExprLambda() {",
+            "    Function<SwitchExpr,Object> f = (s) -> switch (s.i) { case 3, 4, 5 -> new Object(); default -> \"hello\"; };",
```
Comment (lazaroclapp) [inline jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwaySwitchTests.java:170]: I suppose the only thing to test here is whether a crash can happen or not, since we can't really add any interesting nullability test here until we support nullability of generics to some degree...

**Review by lazaroclapp — APPROVED** [review]
LGTM

File: jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwaySwitchTests.java (hunk 1 above)
Comment (msridhar) [reply jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwaySwitchTests.java:170]: Yes, exactly.  Sorry, I had set this to automerge, but I'll add a comment in a follow-up PR
