### PR TITLE
Accept any annotation with simple name `Contract`, and change reporting of invalid contract annotations

### LINKED ISSUE #1215: Invalid `@Contract` declaration reported for code that doesn't exist
Running NullAway on this class:

```java
import java.time.Instant;

import org.jspecify.annotations.Nullable;

class Foo {

	@Nullable Instant instant;

	Foo(@Nullable Instant instant) {
		this.instant = instant;
	}
}
```

results in

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (java-compile) on project …: Compilation failure: Compilation failure: 
[ERROR] …/src/main/java/Foo.java:[13] [NullAway] Invalid @Contract annotation detected for method isNull(). It contains the following uparseable clause: _ -> this (incorrect number of arguments in the clause's antecedent [1], should be the same as the number of arguments in for the method [0]).
[ERROR]     (see http://t.uber.com/nullaway )
```

Maven: 3.9.9
NullAway: 0.12.7
Java: OpenJDK Runtime Environment Temurin-24.0.1+9 (build 24.0.1+9)

### LINKED ISSUE #1222: AssertJ's fail* methods do not qualify as throw statements
AssertJ allows users to write their own `*Assert` classes by extending `AbstractAssert` which is very convenient if you want to have a TCK with AssertJ's fluent API for your own domain objects.

Unfortunately, NullAway ignores methods in `AbstractAssert` that meant to stop the control flow and throw an exception: `fail*`, `failure`, etc. methods.

For example:

```java
import org.assertj.core.api.AbstractAssert;
import org.jspecify.annotations.Nullable;

class DemoAssert<SELF extends DemoAssert<SELF>> extends AbstractAssert<SELF, DemoAssert.DemoConcept> {

    protected DemoAssert(DemoConcept demoConcept) {
        super(demoConcept, DemoAssert.class);
    }

    static DemoAssert<?> assertThat(DemoConcept actual) {
        return new DemoAssert<>(actual);
    }

    SELF hasLongerValue() {
        if (actual.getValue() == null) {
            failWithMessage("Value is null");
        }
        if (actual.getValue().length() < 5) {
            failWithMessage("Value is shorter than 5 characters: <%s>", actual.getValue());
        }

        return (SELF) this;
    }

    static class DemoConcept {
        @Nullable String getValue() {
            return null;
        }
    }

    public static void main(String[] args) {
        DemoAssert.assertThat(new DemoConcept()).hasLongerValue();
    }
}
```
produces the following error:
```
java: [NullAway] dereferenced expression actual.getValue() is @Nullable
    (see http://t.uber.com/nullaway )
```

But in this setup the `.length()` call cannot cause an NPE since there is a null-check before and `failWithMessage` throws an exception so the execution cannot reach the `.length()` call on a null reference.

Workaround: `else if (actual.getValue().length() < 5) { ... }` which is cleaner if you ask me but the reproducer above should be ok too and there are cases where there is no workaround:
```java
String demo() { // return type is implicit @NonNull
    if (actual.getValue() == null) {
        failWithMessage("Value is null!");
    }
    return actual.getValue();
}
```

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1222 
Fixes #1215 

We make the following changes to NullAway's handling of `@Contract` annotations.  First, NullAway now treats any annotation with simple name `Contract` as a contract annotation, not just the JetBrains `@Contract`.  This improves the user experience when using third-party libraries containing non-Jetbrains `@Contract` annotations on public APIs, as those annotation types no longer need to be specified as a custom contract annotation to be picked up by NullAway.  (The custom contract annotation option is still supported, in case someone wants to use an annotation as a contract that doesn't have simple name `Contract`.)

Second, NullAway now only reports errors for malformed `@Contract` annotations on the corresponding method declaration, _not_ on calls to the method.  Reporting malformed `@Contract` errors on calls to methods was a bad behavior, since the method declaration could be in a library that cannot be easily modified.

It's possible this change will lead to unexpected behavior, if users were writing non-Jetbrains annotations named `@Contract` and with similar arguments to `@Contract` but did not want them used by NullAway.  But this seems unlikely, so we go ahead and make this change without an option to disable it.  We can add such an option later if we hear about any issues.

## Summary by CodeRabbit

* **New Features**
  * Broader contract recognition (treats simple-name "Contract" as a contract) and contract checking enabled by default.

* **Bug Fixes**
  * Stricter contract validation: unknown constraint values now report explicit errors; known but non-checkable constraints mark contracts unsupported.
  * Invalid-contract diagnostics moved to method declarations (fewer call-site reports).
  * Safer annotation-value handling to avoid runtime type errors.

* **Tests**
  * Added tests for custom/non‑JetBrains and malformed contract annotations.

* **Documentation**
  * Minor wording and Javadoc fixes.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java [hunk 1]
```diff
@@ -123,15 +126,32 @@ static String[] getAntecedent(
   static @Nullable String getContractString(Symbol.MethodSymbol methodSymbol, Config config) {
     for (AnnotationMirror annotation : methodSymbol.getAnnotationMirrors()) {
       String name = AnnotationUtils.annotationName(annotation);
-      if (config.isContractAnnotation(name)) {
+      if (hasSimpleNameContract(name) || config.isContractAnnotation(name)) {
         return NullabilityUtil.getAnnotationValue(methodSymbol, name);
       }
     }
     return null;
   }
```
[the remark this answers is not in the document]
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java:134]: `NullabilityUtil.getAnnotationValue` is now defensive against the classcastexception

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java [hunk 2]
```diff
@@ -213,7 +213,10 @@ public static Stream<? extends AnnotationMirror> getAllAnnotations(Symbol symbol
         elementValues.entrySet()) {
       ExecutableElement elem = entry.getKey();
       if (elem.getSimpleName().contentEquals("value")) {
-        return (String) entry.getValue().getValue();
+        Object value = entry.getValue().getValue();
+        if (value instanceof String) {
+          return (String) value;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:218]: With this change, what happens to an `@Contract` annotation that doesn't have a `value` field or has a non-String `value` field?

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java [hunk 3]
```diff
@@ -272,24 +271,7 @@ public NullnessHint onDataflowVisitMethodInvocation(
...
-              analysis
-                  .getErrorBuilder()
-                  .createErrorDescription(
-                      new ErrorMessage(
-                          ErrorMessage.MessageTypes.ANNOTATION_VALUE_INVALID, errorMessage),
-                      tree,
-                      analysis.buildDescription(tree),
-                      state,
-                      null));
+          // invalid, but we report an error only on method declarations
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java:274]: Note that we have moved the logic for syntactically validating contracts only when we are also checking that the annotated method satisfies the contract. I think this is fine, but it might lead to lack of user visible information for the cases where they are using contracts in "trust the annotation" mode yet see errors pop up that the contract should suppress, without realizing it is because the contract string is malformed.

I think in modern NullAway it makes sense that if you are adding custom contracts to your codebase you are checking them too and not just trusting, but it is a change we probably want to note in the changelog somewhere :)

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java [hunk 4]
```diff
@@ -123,15 +126,32 @@ static String[] getAntecedent(
...
 
+  /**
+   * Checks if the input string, which is a qualified name, has simple name "Contract".
+   *
+   * @param input the qualified name to check
+   * @return true if the simple name is "Contract", false otherwise
+   */
+  private static boolean hasSimpleNameContract(String input) {
+    int lastDot = input.lastIndexOf('.');
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java:143]: Do we ever want to support an inner class as a contract? E.g. `Foo$[Bar$]Contract`? Probably not for now, but just want to note this requires `Contract` to be a top-level class :)

**Review by lazaroclapp — APPROVED** [review]
Minor notes and questions, but LGTM!

File: nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullabilityUtil.java:218]: I believe it will be silently ignored; see response to next comment.

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java:274]: This is a good point.  My overall thinking was that we want to get to a point where contract validation is on by default rather than off (just opened #1296 on that), so this checking would also happen by default.  For now, though, I wonder if we should do the malformedness checking by default, to avoid weird surprises like the one you mention.  @lazaroclapp thoughts?

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java (hunk 4 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java:143]: Actually I think inner classes happen to work already; see [here](https://github.com/uber/NullAway/blob/02221408699c6a9beef090c5ae411a9df7033a4f/nullaway/src/test/java/com/uber/nullaway/ContractsTests.java#L91).  I think the way that `javac` works we see source-level names, not bytecode-level, so `$` doesn't get used.  In any case, I don't think we want to go further out of our way to support this case :-)

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java (hunk 3 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java:274]: That's not a bad idea. We can run the malformedness checking by default and then honor the flag on whether we should check for contract correctness further inside the corresponding handler, right? I say we should go for it if it's an easy change. Otherwise, I don't hate the idea of flipping contract validation defaults on the same release that includes this change. It only affects codebases with `@Contract` in their annotated code, no?

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java (hunk 4 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractUtils.java:143]: Ah, right. Missed that we are already testing that. The whole confusion in Java between `a.b.c.D.E` and `a.b.c.D$E` depending on what level your tool works at is a bit annoying :sweat_smile:

File: nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/contract/ContractHandler.java:274]: I changed things to run the malformedness checking by default, as you suggested.

When we turn on contract validation by default, yes, that would only affect codebases with `@Contract` in their annotated code.
