### PR TITLE
Properly handle invocation of anonymous class constructor with parameters

### LINKED ISSUE #102: False positive with anonymous class
It appears that constructing an anonymous instance with a nullable parameter doesn't get inspected correctly.

```
/.../AbstractLinkedDeque.java:346: error: [NullAway] passing @Nullable parameter 'first'
where @NonNull is required
    return new AbstractLinkedIterator(first) {
                                      ^
```

```java
public PeekingIterator<E> iterator() {
  return new AbstractLinkedIterator(first) {
    @Override @Nullable E computeNext() {
      return getNext(cursor);
    }
  };
}

abstract class AbstractLinkedIterator implements PeekingIterator<E> {
  @Nullable E previous;
  @Nullable E cursor;

  AbstractLinkedIterator(@Nullable E start) {
    cursor = start;
  }
  ...
}
```

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #102.  We now treat the invocation as if it were directly invoking the constructor of the superclass, so appropriate nullability annotations are checked.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -1850,7 +1864,43 @@ private String errMsgForInitializer(Set<Element> uninitFields) {
...
+  @Nullable
+  private static Symbol.MethodSymbol findSuperConstructorInType(
+      Symbol.MethodSymbol methodSymbol, Type superType, Types types) {
+    Preconditions.checkArgument(methodSymbol.isConstructor(), "only accepts constructor methods");
+    Scope scope = superType.tsym.members();
+    for (Symbol sym : scope.getSymbolsByName(methodSymbol.name)) {
+      if (sym != null
+          && !sym.isStatic()
+          && ((sym.flags() & Flags.SYNTHETIC) == 0)
+          && sym.name.contentEquals(methodSymbol.name)
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Is this always `init` or such? If so, maybe should be comparing with a constant? If not, how are they supposed to be the same? Just curious :)

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 2]
```diff
@@ -302,11 +305,22 @@ public Description matchNewClass(NewClassTree tree, VisitorState state) {
...
+      // passing parameters to constructor of anonymous class
+      // this constructor just invokes the constructor of the superclass, and
+      // in the AST does not have the parameter nullability annotations from the superclass.
+      // so, treat as if the superclass constructor is being invoked directly
+      // see https://github.com/uber/NullAway/issues/102
+      Type supertype = state.getTypes().supertype(methodSymbol.owner.type);
+      Symbol.MethodSymbol superConstructor =
+          findSuperConstructorInType(methodSymbol, supertype, state.getTypes());
+      methodSymbol = superConstructor;
+    }
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Error out if `findSuperConstructorInType` returns `null`? Or keep the original `methodSymbol`? Or assert this is impossible?

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 3]
```diff
@@ -302,11 +305,25 @@ public Description matchNewClass(NewClassTree tree, VisitorState state) {
...
+      // this constructor just invokes the constructor of the superclass, and
+      // in the AST does not have the parameter nullability annotations from the superclass.
+      // so, treat as if the superclass constructor is being invoked directly
+      // see https://github.com/uber/NullAway/issues/102
+      Type supertype = state.getTypes().supertype(methodSymbol.owner.type);
+      Symbol.MethodSymbol superConstructor =
+          findSuperConstructorInType(methodSymbol, supertype, state.getTypes());
+      if (superConstructor == null) {
+        throw new RuntimeException("must find constructor in supertype");
+      }
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: 👍

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Yeah, this should always be "<init>".  I can clean this up, thx
