### PR TITLE
Substitute inferred `@NonNull` types for generic method inference

### LINKED ISSUE #1444: Unexpected errors from contract checking with `!null` return value
We're facing a similar issue to #1440 in the junit-framework build.

In our case, the contract is defined like this:

```java
@Contract("null, _ -> fail; !null, _ -> param1")
public static <T> T notNull(@Nullable T object, String message) throws PreconditionViolationException {
	condition(object != null, message);
	return object;
}
```

... and use like this in a `@NullMarked` package:

```java
public class DynamicContainer {

	final Stream<? extends DynamicNode> children;

	DynamicContainer(DefaultConfiguration configuration) {
		this.children = Preconditions.notNull(configuration.children, "children must not be null");
	}

	// ...
}
```

The `notNull` method is used ~500 times in the codebase and this is the only occurrence where 0.13.0 fails. Maybe it's due to `configuration.children` being generic with a wildcard (`@Nullable Stream<? extends DynamicNode>`)?

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1444 

In certain cases, like the test from #1444 added here, `javac` adds a `@Nullable` annotation to a type incorrectly as part of its inference.  Here, for a call from the test:

```java
@NullMarked
public class Test {
    static class DefaultConfiguration {
        final @Nullable Stream<? extends String> children;
    }
    final Stream<? extends String> children;
    Test(DefaultConfiguration configuration) {
        // relevant call
        this.children = notNull(configuration.children, "children must not be null");
    }
    public static <T> T notNull(@Nullable T object, String message) {
        throw new RuntimeException("todo");
    }
}
```
`javac`s inferred type for the return of the `notNull` call matches the inferred parameter type exactly, `@Nullable Stream<...>`.  But, when applying JSpecify rules, the return cannot be `@Nullable`.  To fix this, add inferred `@NonNull` qualifiers along with `@Nullable` when doing a substitution inside a type.

## Summary by CodeRabbit

* **Bug Fixes**
  * Simplified printing of error/unknown generic types to show only the simple type name.
  * Improved type-variable substitution so inferred nullability is applied for both nullable and non-null cases.

* **Tests**
  * Added/updated tests covering generic method type inference and JSpecify/Nullability behaviors (includes a new scenario for issue1444).

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericTypePrettyPrintingVisitor.java [hunk 1]
```diff
@@ -89,6 +89,13 @@ public String visitArrayType(Type.ArrayType t, @Nullable Void unused) {
     return sb.append(" []").toString();
   }
 
+  @Override
+  public String visitErrorType(Type.ErrorType t, @Nullable Void unused) {
+    // this arises for our synthetic @Nullable and @NonNull annotations; we just return the simple
+    // name
+    return t.tsym.getSimpleName().toString();
+  }
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericTypePrettyPrintingVisitor.java:97]: Drive-by fix to make printed errors more readable, by printing e.g. `@NonNull` instead of `@nullaway.synthetic.NonNull`
