### PR TITLE
JSpecify: preserve explicit nullability annotations on type variables when performing substitutions

### LINKED ISSUE #1091: Mismatched type parameter nullability
Upgrading from `0.12.1` to `0.12.2` and I am confused by these new warnings.

```console
> Task :caffeine:compileJava
/Users/ben/projects/caffeine/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java:3180: warning: [NullAway] Cannot pass parameter of type Function<@org.jspecify.annotations.Nullable V, @org.jspecify.annotations.Nullable V>, as formal parameter has type Function<V, V>, which has mismatched type parameter nullability
            .map(node -> nodeToCacheEntry(node, transformer))
                                                ^
    (see http://t.uber.com/nullaway )
  Did you mean '@SuppressWarnings("NullAway") <T> T snapshot(Iterable<Node<K, V>> iterable, Function<@Nullable V, @Nullable V> transformer,'?
```
```console
/Users/ben/projects/caffeine/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java:4014: warning: [NullAway] Cannot pass parameter of type Function<@org.jspecify.annotations.Nullable V, @org.jspecify.annotations.Nullable V>, as formal parameter has type Function<V, V>, which has mismatched type parameter nullability
      return (node == null) ? null : cache.nodeToCacheEntry(node, transformer);
                                                                  ^
    (see http://t.uber.com/nullaway )
  Did you mean '@SuppressWarnings("NullAway") @Override public @Nullable CacheEntry<K, V> getEntryIfPresentQuietly(K key) {'?
```

The `snapshot` method and `nodeToCacheEntry` method both use the same types for the `transformer` parameter.
```java
  <T> T snapshot(Iterable<Node<K, V>> iterable, Function<@Nullable V, @Nullable V> transformer,
      Function<Stream<CacheEntry<K, V>>, T> mappingFunction)

  @Nullable CacheEntry<K, V> nodeToCacheEntry(
      Node<K, V> node, Function<@Nullable V, @Nullable V> transformer)
```

The other warning is similar. It appears to be a regression.

Note that you might have to use `--rerun`, `--rerun-tasks` or `--no-build-cache` to force recompilations.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1091 

Consider the following code:
```java
abstract class Test {
  abstract <V> @Nullable V foo(Function<@Nullable V, @Nullable V> f);
  void testPositive(Function<String, String> f) {
     this.<String>foo(f); // error
  }
} 
```
The call to `foo` should not type check.  Since the type of its parameter `f` is `Function<@Nullable V, @Nullable V>`, with explicit `@Nullable` annotations on the type variables, any `Function` passed to `foo` must have `@Nullable` type arguments.  In typechecking this code, NullAway previously substituted the type arguments for the type variables in `foo` just using built-in `javac` routines.  But, this would yield a formal parameter type `Function<String, String>`, as the `javac` routine would not retain the explicit type arguments in the right places.  So we would miss reporting an error.  This PR fixes the substitutions and re-introduces the annotations on type variables, so we get the type `Function<@Nullable String, @Nullable String>` for the formal parameter at the call, and report an error correctly.  Substitutions were broken in other cases as well; substituting `@Nullable V` for `@Nullable V` (where `V` is a type variable) yielded just `V`, which led to false positives (like #1091).

The main logic changes are in `TypeSubstitutionUtils`.  We add a new `RestoreNullnessAnnotationsVisitor` and use it to restore nullability annotations from type variables after performing a substitution.

We also extract the `TypeMetadataBuilder` logic to a top-level source file, and add new methods as needed for this PR.  Some of this could have been split into a separate PR but it's a bit of a pain to extract it now.

### CODE REVIEW

File: nullaway/src/main/java/com/uber/nullaway/generics/TypeSubstitutionUtils.java [hunk 1]
```diff
@@ -1,9 +1,18 @@
 package com.uber.nullaway.generics;
```
Comment (akshayutture) [inline nullaway/src/main/java/com/uber/nullaway/generics/TypeSubstitutionUtils.java:1]: What kind of substitution are we referring to here exactly? And why are nullability annotations from type variables lost after performing a substitution - Could you clarify more in the diff description?

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java [hunk 2]
```diff
@@ -634,13 +634,14 @@ public static void compareGenericTypeParameterNullabilityForCall(
       }
       if (enclosingType != null) {
         invokedMethodType =
-            TypeSubstitutionUtils.memberType(state.getTypes(), enclosingType, methodSymbol);
+            TypeSubstitutionUtils.memberType(state.getTypes(), enclosingType, methodSymbol, config);
```
Comment (akshayutture) [inline nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:637]: Is the passing around of the config variable everywhere required for this bug fix? I don't see it being used anywhere.

Or is it an unrelated change which has been combined with this PR? If so, can we clarify this in the PR description?

**Review by akshayutture — APPROVED** [review]

File: nullaway/src/main/java/com/uber/nullaway/generics/TypeSubstitutionUtils.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/TypeSubstitutionUtils.java:1]: PR description is updated

File: nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/generics/GenericsChecks.java:637]: The `Config` object is required for this bug fix.  It is stored in an instance field of `RestoreNullnessAnnotationsVisitor` and used to check whether an annotation should be treated as `@Nullable` or `@NonNull` here:

https://github.com/uber/NullAway/pull/1143/files#diff-a6bb8226bed276672e56b162bca51775aa7ad9c2d3fc69c787bc96e36ce33507R137-R138
