### PR TITLE
Fix library modeling for varargs arrays

### LINKED ISSUE #1481: library models for nullable varargs not working correctly in JSpecify mode
Currently, if you make a varargs argument an explicity nullable parameter via a custom `LibraryModels` object, that applies to the varargs array elements, not the varargs array itself.  In JSpecify mode, we should model this correctly: an explicitly nullable parameter should apply to the varargs array itself, and one should use `nestedAnnotationsForMethods` to mark the contents of the varargs array (individual varargs array elements) as `@Nullable`.  This is a backwards-incompatible change to library modeling so we should bump our minor version when doing so.

We should carefully check our built-in library models for any potential impacts before committing this.

Fix this before fixing #1480

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1481, which should enable us to handle #1480 

This gives us the ability to model more nullability scenarios for varargs arrays via library models.  For example, we can now write a library model for a method like [`Objects.hash(@Nullable Object @Nullable ...)`](https://github.com/jspecify/jdk/blob/cf198c06e3bd59572304f866b5cbf70781112f55/src/java.base/share/classes/java/util/Objects.java#L142) that can accept both a `@Nullable` array argument and `@Nullable` individual arguments at call sites.

To do this, we had to more cleanly separate library modeling of the nullability of the varargs array itself versus its contents.  To this end, we add a new `Handler.onOverrideMethodInvocationVarargsArrayNullability` method for modeling the nullability of the array.  Now, `Handler.onOverrideMethodInvocationParametersNullability` only handles the nullability of the varargs array contents, i.e., whether individual `@Nullable` arguments can be passed at call sites.  This separation and new method required fixes and handling in `LibraryModelsHandler` and `RestrictiveAnnotationHandler`.  

Sorry for the size of this PR.  Suggested guide to reviewing:

* Read the new test inputs, `NullUnmarkedVarargsWithModel` and `NullMarkedVarargsWithModel`
* Read the changes to the library model for the above two classes in `TestLibraryModels`
* Read the new tests in `VarargsLibraryModelsTests`
* Read the code changes

## Summary by CodeRabbit

* **New Features**
  * Add an override hook to control varargs-array nullability, aggregated across handlers.
  * JSpecify-aware generics checks for annotated method calls; JetBrains NotNull now can mark varargs arrays as non-null.
  * Library models distinguish varargs array nullability from element nullability.

* **Bug Fixes**
  * More accurate per-argument null-safety checks for varargs; skip checks when overridden or modeled as safe.

* **Tests**
  * New varargs-focused library-model tests covering JSpecify scenarios.

### CODE REVIEW

File: test-library-models/src/main/java/com/uber/nullaway/testlibrarymodels/TestLibraryModels.java [hunk 1]
```diff
@@ -169,59 +188,103 @@ public ImmutableSetMultimap<MethodRef, Integer> methodTypeVariablesWithNullableU
...
+                        new TypePathEntry(WILDCARD_BOUND, 1)))))
+        .put(
+            methodRef(
+                "com.uber.lib.unannotated.NestedAnnots",
+                "multipleArgs(com.uber.lib.unannotated.NestedAnnots<java.lang.String>,com.uber.lib.unannotated.NestedAnnots<java.lang.Integer>)"),
+            ImmutableSetMultimap.of(
+                1,
+                new NestedAnnotationInfo(
+                    Annotation.NULLABLE, ImmutableList.of(new TypePathEntry(TYPE_ARGUMENT, 0)))))
+        .put(
```
Comment (msridhar) [inline test-library-models/src/main/java/com/uber/nullaway/testlibrarymodels/TestLibraryModels.java:256]: Relevant changes start here.  The rest of the changes stem from having to switch from an `of()` constructor to using a builder

File: test-library-models/src/test/java/com/uber/nullaway/CustomLibraryModelsTests.java [hunk 2]
```diff
@@ -30,7 +30,10 @@
 import org.junit.Rule;
 import org.junit.Test;
 import org.junit.rules.TemporaryFolder;
+import org.junit.runner.RunWith;
+import org.junit.runners.JUnit4;
 
+@RunWith(JUnit4.class)
```
Comment (msridhar) [inline test-library-models/src/test/java/com/uber/nullaway/CustomLibraryModelsTests.java:36]: Drive by fix

File: nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java [hunk 3]
```diff
@@ -148,9 +160,62 @@ public NullnessHint onDataflowVisitFieldAccess(
...
+      for (NestedAnnotationInfo nestedAnnotation : nestedAnnotations.get(varargsIndex)) {
+        // check if it's for the array element
+        if (nestedAnnotation.typePath().size() == 1
+            && nestedAnnotation.typePath().get(0).kind() == ARRAY_ELEMENT) {
+          // this is a nested annotation for the varargs array element, which applies when
+          // individual parameters are passed
+          argumentPositionNullness[varargsIndex] =
+              nestedAnnotation.annotation() == Annotation.NULLABLE ? NULLABLE : NONNULL;
+          break;
+        }
```
[the remark this answers is not in the document]
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java:183]: @msridhar do we generally, anywhere at all, attempt to deal with contradictory models for the same method and location? I guess the code rabbit reported issue seems unlikely to me given most codebases load a single set of library models, but, well, possible.

File: nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java [hunk 4]
```diff
@@ -148,9 +160,54 @@ public NullnessHint onDataflowVisitFieldAccess(
...
+      OptimizedLibraryModels optimizedLibraryModels = getOptLibraryModels(context);
+      boolean nullableFromModel =
+          optimizedLibraryModels.explicitlyNullableParameters(methodSymbol).contains(varargsIndex);
+      boolean nonNullFromModel =
+          optimizedLibraryModels.nonNullParameters(methodSymbol).contains(varargsIndex);
+      if (nullableFromModel && nonNullFromModel) {
+        throw new IllegalStateException(
+            String.format(
+                "Library models give conflicting varargs array nullability for method %s",
+                methodSymbol.getQualifiedName()));
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java:207]: [See other comment under the code rabbit comment] Yeah, we actually check this here! Which is equivalent to what the code rabbit comment is complaining about above, no? (We should iterate over all the models for the var args there and error out if we see two contradictory explicit models.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 5]
```diff
@@ -2041,7 +2041,9 @@ private Description handleInvocation(
       List<? extends ExpressionTree> actualParams) {
     List<VarSymbol> formalParams = methodSymbol.getParameters();
 
-    InvocationArguments invArgs = new InvocationArguments(tree, methodSymbol.type.asMethodType());
+    Type.MethodType invokedMethodType =
+        handler.onOverrideMethodType(methodSymbol, methodSymbol.type.asMethodType(), state);
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Not sure I understand. Is this change also related to var args library models handling? This handler extension point hasn't changed and I see no other changes to our handling of `invArgs`. What behavior does this change modify?

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 6]
```diff
@@ -2106,38 +2112,29 @@ private Description handleInvocation(
...
-              return;
-            }
-            mayActualBeNull = mayBeNullExpr(state, actual);
+            VarSymbol varargsFormalParam = formalParams.get(formalParams.size() - 1);
+            // when is the varargs array itself @NonNull?
+            // 1. For @NullMarked methods, as long as there is no @Nullable annotation
+            Nullness varargsArrayNullness =
+                (isMethodAnnotated && !Nullness.varargsArrayIsNullable(varargsFormalParam, config))
+                    ? Nullness.NONNULL
+                    : null;
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:2122]: Why `null` and not `Nullness.NULLABLE`? I get it doesn't matter since we only ever compare against `NONNULL`, but feels mildly inconsistent if there isn't a real reason. Or does this branch mean nullness is unknown for the var args somehow?

File: nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java [hunk 7]
```diff
@@ -222,6 +225,32 @@ default boolean onOverrideFieldNullability(Symbol field) {
...
+   * <p>This hook is intentionally separate from {@link
+   * #onOverrideMethodInvocationParametersNullability(Context, Symbol.MethodSymbol, boolean,
+   * Nullness[])}. A single parameter-slot nullness value is not expressive enough for varargs,
+   * where the array and its elements can have different nullability.
+   *
+   * @param context The current context.
+   * @param methodSymbol The method symbol for the method in question.
+   * @param isAnnotated A boolean flag indicating whether the called method is annotated
+   * @param varargsArrayNullness current value for the varargs array nullability, or {@code null} if
+   *     none
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/handlers/Handler.java]: We might want to copy the language of the other handler method to the effect of:

```
Some entries may be {@code null}, indicating upstream handlers and the base analysis consider the parameter to be nullness-unknown,
```

here. I got confused when originally looking at `NullAway.java` on this point 😉

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 6 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:2122]: Never mind. I see why now: https://github.com/uber/NullAway/pull/1485/changes#r2901129747, I think

**Review by lazaroclapp — COMMENTED** [review]
Actually, got a chance to look at it today. Might need a more careful glance at the logic in `NullAway.java` itself, since I ended up rushing a bit there, but I feel reasonably convinced of everything else.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 5 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java]: Yeah, this change is unnecessary.  I will undo it.

File: nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java:183]: Fixed now

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 6 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:2122]: Yes, sorry for the confusion, I addressed the other comment and improved the Javadoc

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 8]
```diff
@@ -2108,38 +2114,29 @@ private Description handleInvocation(
...
+            // 2. For @NullUnmarked methods, there should be an explicit @NonNull annotation.  This
+            // is handled by the RestrictiveAnnotationHandler
+            // 3. Library model indicating it is @NonNull (handled in LibraryModelsHandler)
+            varargsArrayNullness =
+                handler.onOverrideMethodInvocationVarargsArrayNullability(
+                    state.context, methodSymbol, isMethodAnnotated, varargsArrayNullness);
```
[the remark this answers is not in the document]
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:2128]: NullAway infers the nullability of local variables; they should not be annotated
