### PR TITLE
Reason about key set iteration for subtypes of Map

### LINKED ISSUE #558: Reasoning about iteration over keySet doesn't work for ImmutableMap
Test case:
```java
public class Test {
  public void keySetStuff(com.google.common.collect.ImmutableMap<Object Object> m) {
    for (Object k: m.keySet()) {
      m.get(k).toString(); // we still get a warning here
    }
  }
}
```
Fixing this is not hard, but doing it properly requires some refactoring to thread around a `VisitorState` to more places.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #558 

Most of the changes here are to thread around a `VisitorState` instead of a `Types` object, which allows us to use recommended Error Prone APIs to get a reference to a `Type` object and do subtype tests.

### CODE REVIEW

**Comment by msridhar** [comment]
Will definitely run perf tests on this one

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java [hunk 1]
```diff
@@ -566,9 +570,10 @@ private void handleEnhancedForOverKeySet(
             AccessPath.mapWithIteratorContentsKey(mapNode, lhs, apContext);
         if (mapWithIteratorContentsKey != null) {
           // put sanity check here to minimize perf impact
-          if (!isCallToMethod(rhsInv, "java.util.Set", "iterator")) {
+          if (!isCallToMethod(rhsInv, SET_TYPE_SUPPLIER, "iterator")) {
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java:573]: This is a key change; we allow `iterator()` to come from a subtype of `Set` (since, e.g., `ImmutableMap.keySet()` returns an `ImmutableSet`)

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java [hunk 2]
```diff
@@ -590,9 +595,10 @@ private void handleEnhancedForOverKeySet(
                 .getMapGetIteratorContentsAccessPath((LocalVariableNode) receiver);
         if (mapGetPath != null) {
           // put sanity check here to minimize perf impact
-          if (!isCallToMethod(methodInv, "java.util.Iterator", "next")) {
+          if (!isCallToMethod(methodInv, ITERATOR_TYPE_SUPPLIER, "next")) {
```
Comment (msridhar) [inline nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java:598]: This is a key change; we allow `next()` to come from a subtype of `Iterator` (didn't see a need for this yet but I could easily see it happening)

**Comment by msridhar** [comment]
Confirmed that perf does not regress with this change.  The coverage reduction is due to some additional newlines from formatting (sigh)

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPath.java [hunk 3]
```diff
@@ -547,37 +548,16 @@ public String toString() {
...
-    }
-    if (symbol.getParameters().size() != numParams) {
-      return false;
-    }
-    Symbol owner = symbol.owner;
-    if (owner.getQualifiedName().toString().equals("java.util.Map")) {
-      return true;
-    }
-    com.sun.tools.javac.util.List<Type> supertypes = types.closure(owner.type);
-    for (Type t : supertypes) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPath.java:563]: So, presumably, this part would still work for both `Map` and `ImmutableMap`. It's just that using a `Supplier<Type>` is cleaner and we noticed the refactoring opportunity when adding the one for sets. Correct?

**Review by lazaroclapp — APPROVED** [review]
LGTM!

File: nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPath.java (hunk 3 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPath.java:563]: Yes, that's exactly right.  I also think it's possibly more performant than looping over the supertypes each time; there may be some internal cache for subtype queries
