### PR TITLE
Fix new Error Prone 2.4.0 detected issues.

### LINKED ISSUE #402: [Cleanup] Remove suppressions added in #400 and fix corresponding code
See #400

### PR DESCRIPTION
**Pull request by lazaroclapp**
This removes the suppressions introduced in #400 and makes more permanent fixes.

Fixes #402.

### CODE REVIEW

File: jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java [hunk 1]
```diff
@@ -279,8 +278,7 @@ public static void annotateBytecodeInJar(
     // Do not use JarInputStream in place of JarFile/JarEntry. JarInputStream misses MANIFEST.MF
     // while iterating over the entries in the stream.
     // Reference: https://bugs.openjdk.java.net/browse/JDK-8215788
-    for (Enumeration<JarEntry> entries = inputJar.entries(); entries.hasMoreElements(); ) {
-      JarEntry jarEntry = entries.nextElement();
+    for (JarEntry jarEntry : inputJar.stream().collect(ImmutableList.toImmutableList())) {
```
Comment (msridhar) [inline jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:281]: In these cases can we do a `forEach()` on the stream rather than collecting in a list and looping over that?  That seems a bit cleaner and avoids copying to another list.

File: jar-infer/jar-infer-lib/src/test/java/com/uber/nullaway/jarinfer/EntriesComparator.java [hunk 2]
```diff
@@ -40,20 +39,15 @@
...
-  @SuppressWarnings("JdkObsolete")
   public static boolean compareEntriesInJars(String jarFile1, String jarFile2) throws IOException {
     Preconditions.checkArgument(jarFile1.endsWith(".jar"), "invalid jar file: " + jarFile1);
     Preconditions.checkArgument(jarFile2.endsWith(".jar"), "invalid jar file: " + jarFile2);
     JarFile jar1 = new JarFile(jarFile1);
     Set<String> jar1Entries = new HashSet<>();
-    for (Enumeration<JarEntry> entries = jar1.entries(); entries.hasMoreElements(); ) {
-      jar1Entries.add(entries.nextElement().getName());
-    }
+    jar1.stream().forEach(entry -> jar1Entries.add(entry.getName()));
```
Comment (msridhar) [inline jar-infer/jar-infer-lib/src/test/java/com/uber/nullaway/jarinfer/EntriesComparator.java:47]: Here I would do something like `Set<String> jar1Entries = jar1.stream().map(Entry::getName).collect(Collectors::toSet)`.  Not sure of exact syntax but something like that.  Same for the other similar cases.

File: jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java (hunk 1 above)
Comment (lazaroclapp) [reply jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:281]: No, we can't. The code bellow can throw `IOException`. If that happens within a lambda, we need to catch it there, if it happens within an iteration we can propagate it up.

Comment (msridhar) [reply jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:281]: Maybe add a code comment to that effect?

File: jar-infer/jar-infer-lib/src/test/java/com/uber/nullaway/jarinfer/EntriesComparator.java (hunk 2 above)
Comment (lazaroclapp) [reply jar-infer/jar-infer-lib/src/test/java/com/uber/nullaway/jarinfer/EntriesComparator.java]: Done.

File: jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java (hunk 1 above)
Comment (lazaroclapp) [reply jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:283]: Also done 😄

File: jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java [hunk 3]
```diff
@@ -279,8 +278,9 @@ public static void annotateBytecodeInJar(
     // Do not use JarInputStream in place of JarFile/JarEntry. JarInputStream misses MANIFEST.MF
     // while iterating over the entries in the stream.
     // Reference: https://bugs.openjdk.java.net/browse/JDK-8215788
-    for (Enumeration<JarEntry> entries = inputJar.entries(); entries.hasMoreElements(); ) {
-      JarEntry jarEntry = entries.nextElement();
+    // Note: we can't just put the code below inside stream().forach(), because it can throw
+    // IOException.
+    for (JarEntry jarEntry : inputJar.stream().collect(ImmutableList.toImmutableList())) {
```
[the remark this answers is not in the document]
Comment (msridhar) [reply jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:283]: Ah very cool!  I didn't know you could convert streams to iterators (and iterables) so easily!

[the remark this answers is not in the document]
Comment (lazaroclapp) [reply jar-infer/jar-infer-lib/src/main/java/com/uber/nullaway/jarinfer/BytecodeAnnotator.java:283]: (Just so you know: aware of this note and planning to do a follow up PR, but I haven't had a chance :) Unless someone else wants to go for it, I'll try to follow up early next week)
