### PR TITLE
Fix bug with implicit equals() methods in interfaces

### LINKED ISSUE #897: False positive on equals(nullable) when using NullAway with Java 21.
We are attempting to migrate our codebase from Java 17 to 21. We have run into a peculiar issue where NullAway started producing false positives when calling on `equals()` with a nullable parameter. This did not use to be the case.

**NullAway version:** `0.10.19` and `0.10.21`

**Repro**:
```
import javax.annotation.Nullable;

public class Repro {

    public interface AnInterface {}

    public static boolean foo(AnInterface a, @Nullable AnInterface b) {
        return a.equals(b);
    }
}
```
The above when built with Java 21 (`OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)` results in error:
```
/Repro.java:10: error: [NullAway] passing @Nullable parameter 'b' where @NonNull is required
        return a.equals(b);
                        ^
    (see http://t.uber.com/nullaway )
```

When built with Java 17 (`OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)`
) no error is generated.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #897 

This fixes a regression in our handling of implicit `equals()` methods in interfaces when building on JDK 21.  I see this as an interim fix, until we can fix NullAway to properly always assume / enforce that the parameter of `equals()` is `@Nullable`.  But, I think we should fix the regression in the short term.

### CODE REVIEW

File: nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java [hunk 1]
```diff
@@ -985,4 +985,20 @@ public void cfgConstructionSymbolCompletionFailure() {
             "}")
         .doTest();
   }
+
+  @Test
+  public void testDefaultEqualsInInterfaceTakesNullable() {
```
Comment (msridhar) [inline nullaway/src/test/java/com/uber/nullaway/NullAwayCoreTests.java:990]: Before this PR, this test would fail in the `:nullaway:testJdk21` task

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 2]
```diff
@@ -399,16 +400,31 @@ public Description matchMethodInvocation(MethodInvocationTree tree, VisitorState
...
+    // methods.  This is an adaptation to a change in JDK 18; see
+    // https://bugs.openjdk.org/browse/JDK-8272564
+    if (methodSymbol.owner.isInterface()) {
+      Symbol.MethodSymbol baseSymbol = (Symbol.MethodSymbol) methodSymbol.baseSymbol();
+      if (baseSymbol != methodSymbol && baseSymbol.owner == state.getSymtab().objectType.tsym) {
+        methodSymbol = baseSymbol;
+      }
+    }
+    return methodSymbol;
+  }
```
Comment (yuxincs) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:426]: Correct me if I'm understanding this wrong, but previously we would get a symbol from the interface, which would eventually be considered annotated in the caller (`matchMethodInvocation` and later `handleInvocation`).

Now that we have this special handling to resolve to the base symbol (i.e., from `java.lang.Object`), which would be considered unannotated (everything from the JDK is unannotated), and then NullAway won't think that `equals` must have a nonnull param. Right?

If so, this change looks good to me! (I also agree that this is the interim solution and the end goal is for NullAway to enforce nullable on `equals`, but that's for another PR)

**Review by yuxincs — APPROVED** [review]
Just have a clarifying question due to my insufficient knowledge of the codebase, but the change LGTM!

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 2 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:426]: @yuxincs yes, this is exactly correct.
